#include "object.h"
#include "symbol.h"
#include "string.h"
#include "package.h"

DEFINE_CLASS(class_symbol);

object symbol_abort;
object symbol_abs;
object symbol_acons;
object symbol_acos;
object symbol_acosh;
object symbol_add_method;
object symbol_adjoin;
object symbol_adjust_array;
object symbol_adjustable_array_p;
object symbol_allocate_instance;
object symbol_alpha_char_p;
object symbol_alphanumericp;
object symbol_and;
object symbol_append;
object symbol_apply;
object symbol_apropos;
object symbol_apropos_list;
object symbol_aref;
object symbol_arithmetic_error;
object symbol_arithmetic_error_operands;
object symbol_arithmetic_error_operation;
object symbol_array;
object symbol_array_dimension;
object symbol_array_dimension_limit;
object symbol_array_dimensons;
object symbol_array_displacement;
object symbol_array_element_type;
object symbol_array_has_fill_pointer_p;
object symbol_array_in_bounds_p;
object symbol_array_rank;
object symbol_array_rank_limit;
object symbol_array_row_major_index;
object symbol_array_total_size;
object symbol_array_total_size_limit;
object symbol_arrayp;
object symbol_ash;
object symbol_asin;
object symbol_asinh;
object symbol_assert;
object symbol_assoc;
object symbol_assoc_if;
object symbol_assoc_if_not;
object symbol_atan;
object symbol_atanh;
object symbol_atom;

object symbol_base_char;
object symbol_base_string;
object symbol_bignum;
object symbol_bit;
object symbol_bit_and;
object symbol_bit_andc1;
object symbol_bit_andc2;
object symbol_bit_eqv;
object symbol_bit_ior;
object symbol_bit_nand;
object symbol_bit_nor;
object symbol_bit_not;
object symbol_bit_orc1;
object symbol_bit_orc2;
object symbol_bit_vector;
object symbol_bit_vector_p;
object symbol_bit_xor;
object symbol_block;
object symbol_boole;
object symbol_boole_1;
object symbol_boole_2;
object symbol_boole_and;
object symbol_boole_andc1;
object symbol_boole_andc2;
object symbol_boole_c1;
object symbol_boole_c2;
object symbol_boole_clr;
object symbol_boole_eqv;
object symbol_boole_ior;
object symbol_boole_nand;
object symbol_boole_nor;
object symbol_boole_orc1;
object symbol_boole_orc2;
object symbol_boole_set;
object symbol_boole_xor;
object symbol_boolean;
object symbol_both_case_p;
object symbol_boundp;
object symbol_break;
object symbol_broadcast_stream;
object symbol_broadcast_stream_streams;
object symbol_built_in_class;
object symbol_butlast;
object symbol_byte;
object symbol_byte_position;
object symbol_byte_size;

object symbol_caaaar;
object symbol_caaadr;
object symbol_caaar;
object symbol_caadar;
object symbol_caaddr;
object symbol_caadr;
object symbol_caar;
object symbol_cadaar;
object symbol_cadadr;
object symbol_cadar;
object symbol_caddar;
object symbol_cadddr;
object symbol_caddr;
object symbol_cadr;
object symbol_call_arguments_limit;
object symbol_call_method;
object symbol_call_next_method;
object symbol_car;
object symbol_case;
object symbol_catch;
object symbol_ccase;
object symbol_cdaaar;
object symbol_cdaadr;
object symbol_cdaar;
object symbol_cdadar;
object symbol_cdaddr;
object symbol_cdadr;
object symbol_cdar;
object symbol_cddaar;
object symbol_cddadr;
object symbol_cddar;
object symbol_cdddar;
object symbol_cddddr;
object symbol_cdddr;
object symbol_cddr;
object symbol_cdr;
object symbol_ceiling;
object symbol_cell_error;
object symbol_cell_error_name;
object symbol_cerror;
object symbol_change_class;
object symbol_char;
object symbol_char_code;
object symbol_char_code_limit;
object symbol_char_downcase;
object symbol_char_equal;
object symbol_char_greaterp;
object symbol_char_int;
object symbol_char_lessp;
object symbol_char_name;
object symbol_char_not_equal;
object symbol_char_not_greaterp;
object symbol_char_not_lessp;
object symbol_char_upcase;
object symbol_char_not_equal_sign;
object symbol_char_less_sign;
object symbol_char_less_or_equal_sign;
object symbol_char_equal_sign;
object symbol_char_greater_sign;
object symbol_char_greater_or_equal_sign;
object symbol_character;
object symbol_characterp;
object symbol_check_type;
object symbol_cis;
object symbol_class;
object symbol_class_name;
object symbol_class_of;
object symbol_clear_input;
object symbol_clear_output;
object symbol_close;
object symbol_clrhash;
object symbol_code_char;
object symbol_coerce;
object symbol_compilation_speed;
object symbol_compile;
object symbol_compile_file;
object symbol_compile_file_pathname;
object symbol_compiled_function;
object symbol_compiled_function_p;
object symbol_compiler_macro;
object symbol_compiler_macro_function;
object symbol_complement;
object symbol_complex;
object symbol_complexp;
object symbol_compute_applicable_methods;
object symbol_compute_restarts;
object symbol_concatenate;
object symbol_concatenated_stream;
object symbol_concatenated_stream_streams;
object symbol_cond;
object symbol_condition;
object symbol_conjugate;
object symbol_cons;
object symbol_consp;
object symbol_constantly;
object symbol_constantp;
object symbol_continue;
object symbol_control_error;
object symbol_copy_alist;
object symbol_copy_list;
object symbol_copy_pprint_dispatch;
object symbol_copy_readtable;
object symbol_copy_seq;
object symbol_copy_structure;
object symbol_copy_symbol;
object symbol_copy_tree;
object symbol_cos;
object symbol_cosh;
object symbol_count;
object symbol_count_if;
object symbol_count_if_not;
object symbol_ctypecase;

object symbol_debug;
object symbol_decf;
object symbol_declaim;
object symbol_declaration;
object symbol_declare;
object symbol_decode_float;
object symbol_decode_universal_time;
object symbol_defclass;
object symbol_defconstant;
object symbol_defgeneric;
object symbol_define_compiler_macro;
object symbol_define_condition;
object symbol_define_method_combination;
object symbol_define_modify_macro;
object symbol_define_setf_expander;
object symbol_define_symbol_macro;
object symbol_defmacro;
object symbol_defmethod;
object symbol_defpackage;
object symbol_defparameter;
object symbol_defsetf;
object symbol_defstruct;
object symbol_deftype;
object symbol_defun;
object symbol_defvar;
object symbol_delete;
object symbol_delete_duplicates;
object symbol_delete_file;
object symbol_delete_if;
object symbol_delete_if_not;
object symbol_delete_package;
object symbol_denominator;
object symbol_deposit_field;
object symbol_describe;
object symbol_describe_object;
object symbol_destructuring_bind;
object symbol_digit_char;
object symbol_digit_char_p;
object symbol_directory;
object symbol_directory_namestring;
object symbol_disassemble;
object symbol_division_by_zero;
object symbol_do;
object symbol_do_star;
object symbol_do_all_symbols;
object symbol_do_external_symbols;
object symbol_do_symbols;
object symbol_documentation;
object symbol_dolist;
object symbol_dotimes;
object symbol_double_float;
object symbol_double_float_epsilon;
object symbol_double_float_negative_epsilon;
object symbol_dpb;
object symbol_dribble;
object symbol_dynamic_extent;
        
object symbol_ecase;
object symbol_echo_stream;
object symbol_echo_stream_input_stream;
object symbol_echo_stream_output_stream;
object symbol_ed;
object symbol_eighth;
object symbol_elt;
object symbol_encode_universal_time;
object symbol_end_of_file;
object symbol_endp;
object symbol_enough_namestring;
object symbol_ensure_directories_exist;
object symbol_ensure_generic_function;
object symbol_eq;
object symbol_eql;
object symbol_equal;
object symbol_equalp;
object symbol_error;
object symbol_etypecase;
object symbol_eval;
object symbol_eval_when;
object symbol_evenp;
object symbol_every;
object symbol_exp;
object symbol_export;
object symbol_expt;
object symbol_extended_char;
        
object symbol_fboundp;
object symbol_fceiling;
object symbol_fdefinition;
object symbol_ffloor;
object symbol_fifth;
object symbol_file_author;
object symbol_file_error;
object symbol_file_error_pathname;
object symbol_file_length;
object symbol_file_namestring;
object symbol_file_position;
object symbol_file_stream;
object symbol_file_string_length;
object symbol_file_write_date;
object symbol_fill;
object symbol_fill_pointer;
object symbol_find;
object symbol_find_all_symbols;
object symbol_find_class;
object symbol_find_if;
object symbol_find_if_not;
object symbol_find_method;
object symbol_find_package;
object symbol_find_restart;
object symbol_find_symbol;
object symbol_finish_output;
object symbol_first;
object symbol_fixnum;
object symbol_flet;
object symbol_float;
object symbol_float_digits;
object symbol_float_precision;
object symbol_float_radix;
object symbol_float_sign;
object symbol_floating_point_inexact;
object symbol_floating_point_invalid_operation;
object symbol_floating_point_overflow;
object symbol_floating_point_underflow;
object symbol_floatp;
object symbol_floor;
object symbol_fmakunbound;
object symbol_force_output;
object symbol_format;
object symbol_formatter;
object symbol_fourth;
object symbol_fresh_line;
object symbol_fround;
object symbol_ftruncate;
object symbol_ftype;
object symbol_funcall;
object symbol_function;
object symbol_function_keywords;
object symbol_function_lambda_expression;
object symbol_functionp;

object symbol_gcd;
object symbol_generic_function;
object symbol_gensym;
object symbol_gentemp;
object symbol_get;
object symbol_get_decoded_time;
object symbol_get_dispatch_macro_character;
object symbol_get_internal_real_time;
object symbol_get_internal_run_time;
object symbol_get_macro_character;
object symbol_get_output_stream_string;
object symbol_get_properties;
object symbol_get_setf_expansion;
object symbol_get_universal_time;
object symbol_getf;
object symbol_gethash;
object symbol_go;
object symbol_graphic_char_p;

object symbol_handler_bind;
object symbol_handler_case;
object symbol_hash_table;
object symbol_hash_table_count;
object symbol_hash_table_p;
object symbol_hash_table_rehash_size;
object symbol_hash_table_rehash_threshold;
object symbol_hash_table_size;
object symbol_hash_table_test;
object symbol_host_namestring;

object symbol_identity;
object symbol_if;
object symbol_ignorable;
object symbol_ignore;
object symbol_ignore_errors;
object symbol_imagpart;
object symbol_import;
object symbol_in_package;
object symbol_incf;
object symbol_initialize_instance;
object symbol_inline;
object symbol_input_stream_p;
object symbol_inspect;
object symbol_integer;
object symbol_integer_decode_float;
object symbol_integer_length;
object symbol_integerp;
object symbol_interactive_stream_p;
object symbol_intern;
object symbol_internal_time_units_per_second;
object symbol_intersection;
object symbol_invalid_method_error;
object symbol_invoke_debugger;
object symbol_invoke_restart;
object symbol_invoke_restart_interactively;
object symbol_isqrt;

object symbol_keyword;
object symbol_keywordp;

object symbol_labels;
object symbol_lambda;
object symbol_lambda_list_keywords;
object symbol_lambda_parameters_limit;
object symbol_last;
object symbol_lcm;
object symbol_ldb;
object symbol_ldb_test;
object symbol_ldiff;
object symbol_least_negative_double_float;
object symbol_least_negative_long_float;
object symbol_least_negative_normalized_double_float;
object symbol_least_negative_normalized_long_float;
object symbol_least_negative_normalized_short_float;
object symbol_least_negative_normalized_single_float;
object symbol_least_negative_short_float;
object symbol_least_negative_single_float;
object symbol_least_positive_double_float;
object symbol_least_positive_long_float;
object symbol_least_positive_normalized_double_float;
object symbol_least_positive_normalized_long_float;
object symbol_least_positive_normalized_short_float;
object symbol_least_positive_normalized_single_float;
object symbol_least_positive_short_float;
object symbol_least_positive_single_float;
object symbol_length;
object symbol_let;
object symbol_let_star;
object symbol_lisp_implementation_type;
object symbol_lisp_implementation_version;
object symbol_list;
object symbol_list_star;
object symbol_list_all_packages;
object symbol_list_length;
object symbol_listen;
object symbol_listp;
object symbol_load;
object symbol_load_logical_pathname_translations;
object symbol_load_time_value;
object symbol_locally;
object symbol_log;
object symbol_logand;
object symbol_logandc1;
object symbol_logandc2;
object symbol_logbitp;
object symbol_logcount;
object symbol_logeqv;
object symbol_logical_pathname;
object symbol_logical_pathname_translations;
object symbol_logior;
object symbol_lognand;
object symbol_lognor;
object symbol_lognot;
object symbol_logorc1;
object symbol_logorc2;
object symbol_logtest;
object symbol_logxor;
object symbol_long_float;
object symbol_long_float_epsilon;
object symbol_long_float_negative_epsilon;
object symbol_long_site_name;
object symbol_loop;
object symbol_loop_finish;
object symbol_lower_case_p;
    
object symbol_machine_instance;
object symbol_machine_type;
object symbol_machine_version;
object symbol_macro_function;
object symbol_macroexpand;
object symbol_macroexpand_1;
object symbol_macrolet;
object symbol_make_array;
object symbol_make_broadcast_stream;
object symbol_make_concatenated_stream;
object symbol_make_condition;
object symbol_make_dispatch_macro_character;
object symbol_make_echo_stream;
object symbol_make_hash_table;
object symbol_make_instance;
object symbol_make_instances_obsolete;
object symbol_make_list;
object symbol_make_load_form;
object symbol_make_load_form_saving_slots;
object symbol_make_method;
object symbol_make_package;
object symbol_make_pathname;
object symbol_make_random_state;
object symbol_make_sequence;
object symbol_make_string;
object symbol_make_string_input_stream;
object symbol_make_string_output_stream;
object symbol_make_symbol;
object symbol_make_synonym_stream;
object symbol_make_two_way_stream;
object symbol_makunbound;
object symbol_map;
object symbol_map_into;
object symbol_mapc;
object symbol_mapcan;
object symbol_mapcar;
object symbol_mapcon;
object symbol_maphash;
object symbol_mapl;
object symbol_maplist;
object symbol_mask_field;
object symbol_max;
object symbol_member;
object symbol_member_if;
object symbol_member_if_not;
object symbol_merge;
object symbol_merge_pathnames;
object symbol_method;
object symbol_method_combination;
object symbol_method_combination_error;
object symbol_method_qualifiers;
object symbol_min;
object symbol_minusp;
object symbol_mismatch;
object symbol_mod;
object symbol_most_negative_double_float;
object symbol_most_negative_fixnum;
object symbol_most_negative_long_float;
object symbol_most_negative_short_float;
object symbol_most_negative_single_float;
object symbol_most_positive_double_float;
object symbol_most_positive_fixnum;
object symbol_most_positive_long_float;
object symbol_most_positive_short_float;
object symbol_most_positive_single_float;
object symbol_muffle_warning;
object symbol_multiple_value_bind;
object symbol_multiple_value_call;
object symbol_multiple_value_list;
object symbol_multiple_value_prog1;
object symbol_multiple_value_setq;
object symbol_multiple_values_limit;

object symbol_name_char;
object symbol_namestring;
object symbol_nbutlast;
object symbol_nconc;
object symbol_next_method_p;
object symbol_nil;
object symbol_nintersection;
object symbol_ninth;
object symbol_no_applicable_method;
object symbol_no_next_method;
object symbol_not;
object symbol_notany;
object symbol_notevery;
object symbol_notinline;
object symbol_nreconc;
object symbol_nreverse;
object symbol_nset_difference;
object symbol_nset_exclusive_or;
object symbol_nstring_capitalize;
object symbol_nstring_downcase;
object symbol_nstring_upcase;
object symbol_nsublis;
object symbol_nsubst;
object symbol_nsubst_if;
object symbol_nsubst_if_not;
object symbol_nsubstitute;
object symbol_nsubstitute_if;
object symbol_nsubstitute_if_not;
object symbol_nth;
object symbol_nth_value;
object symbol_nthcdr;
object symbol_null;
object symbol_number;
object symbol_numberp;
object symbol_numerator;
object symbol_nunion;
object symbol_oddp;
object symbol_open;
object symbol_open_stream_p;
object symbol_optimize;
object symbol_or;
object symbol_otherwise;
object symbol_output_stream_p;
object symbol_package;
object symbol_package_error;
object symbol_package_error_package;
object symbol_package_name;
object symbol_package_nicknames;
object symbol_package_shadowing_symbols;
object symbol_package_use_list;
object symbol_package_used_by_list;
object symbol_packagep;
object symbol_pairlis;
object symbol_parse_error;
object symbol_parse_integer;
object symbol_parse_namestring;
object symbol_pathname;
object symbol_pathname_device;
object symbol_pathname_directory;
object symbol_pathname_host;
object symbol_pathname_match_p;
object symbol_pathname_name;
object symbol_pathname_type;
object symbol_pathname_version;
object symbol_pathnamep;
object symbol_peek_char;
object symbol_phase;
object symbol_pi;
object symbol_plusp;
object symbol_pop;
object symbol_position;
object symbol_position_if;
object symbol_position_if_not;
object symbol_pprint;
object symbol_pprint_dispatch;
object symbol_pprint_exit_if_list_exhausted;
object symbol_pprint_fill;
object symbol_pprint_indent;
object symbol_pprint_linear;
object symbol_pprint_logical_block;
object symbol_pprint_newline;
object symbol_pprint_pop;
object symbol_pprint_tab;
object symbol_pprint_tabular;
object symbol_prin1;
object symbol_prin1_to_string;
object symbol_princ;
object symbol_princ_to_string;
object symbol_print;
object symbol_print_not_readable;
object symbol_print_not_readable_object;
object symbol_print_object;
object symbol_print_unreadable_object;
object symbol_probe_file;
object symbol_proclaim;
object symbol_prog;
object symbol_prog_star;
object symbol_prog1;
object symbol_prog2;
object symbol_progn;
object symbol_program_error;
object symbol_progv;
object symbol_provide;
object symbol_psetf;
object symbol_psetq;
object symbol_push;
object symbol_pushnew;
object symbol_quote;
object symbol_random;
object symbol_random_state;
object symbol_random_state_p;
object symbol_rassoc;
object symbol_rassoc_if;
object symbol_rassoc_if_not;
object symbol_ratio;
object symbol_rational;
object symbol_rationalize;
object symbol_rationalp;
object symbol_read;
object symbol_read_byte;
object symbol_read_char;
object symbol_read_char_no_hang;
object symbol_read_delimited_list;
object symbol_read_from_string;
object symbol_read_line;
object symbol_read_preserving_whitespace;
object symbol_read_sequence;
object symbol_reader_error;
object symbol_readtable;
object symbol_readtable_case;
object symbol_readtablep;
object symbol_real;
object symbol_realp;
object symbol_realpart;
object symbol_reduce;
object symbol_reinitialize_instance;
object symbol_rem;
object symbol_remf;
object symbol_remhash;
object symbol_remove;
object symbol_remove_duplicates;
object symbol_remove_if;
object symbol_remove_if_not;
object symbol_remove_method;
object symbol_remprop;
object symbol_rename_file;
object symbol_rename_package;
object symbol_replace;
object symbol_require;
object symbol_rest;
object symbol_restart;
object symbol_restart_bind;
object symbol_restart_case;
object symbol_restart_name;
object symbol_return;
object symbol_return_from;
object symbol_revappend;
object symbol_reverse;
object symbol_room;
object symbol_rotatef;
object symbol_round;
object symbol_row_major_aref;
object symbol_rplaca;
object symbol_rplacd;
object symbol_safety;
object symbol_satisfies;
object symbol_sbit;
object symbol_scale_float;
object symbol_schar;
object symbol_search;
object symbol_second;
object symbol_sequence;
object symbol_serious_condition;
object symbol_set;
object symbol_set_difference;
object symbol_set_dispatch_macro_character;
object symbol_set_exclusive_or;
object symbol_set_macro_character;
object symbol_set_pprint_dispatch;
object symbol_set_syntax_from_char;
object symbol_setf;
object symbol_setq;
object symbol_seventh;
object symbol_shadow;
object symbol_shadowing_import;
object symbol_shared_initialize;
object symbol_shiftf;
object symbol_short_float;
object symbol_short_float_epsilon;
object symbol_short_float_negative_epsilon;
object symbol_short_site_name;
object symbol_signal;
object symbol_signed_byte;
object symbol_signum;
object symbol_simple_array;
object symbol_simple_base_string;
object symbol_simple_bit_vector;
object symbol_simple_bit_vector_p;
object symbol_simple_condition;
object symbol_simple_condition_format_arguments;
object symbol_simple_condition_format_control;
object symbol_simple_error;
object symbol_simple_string;
object symbol_simple_string_p;
object symbol_simple_type_error;
object symbol_simple_vector;
object symbol_simple_vector_p;
object symbol_simple_warning;
object symbol_sin;
object symbol_single_float;
object symbol_single_float_epsilon;
object symbol_single_float_negative_epsilon;
object symbol_sinh;
object symbol_sixth;
object symbol_sleep;
object symbol_slot_boundp;
object symbol_slot_exists_p;
object symbol_slot_makunbound;
object symbol_slot_missing;
object symbol_slot_unbound;
object symbol_slot_value;
object symbol_software_type;
object symbol_software_version;
object symbol_some;
object symbol_sort;
object symbol_space;
object symbol_special;
object symbol_special_operator_p;
object symbol_speed;
object symbol_sqrt;
object symbol_stable_sort;
object symbol_standard;
object symbol_standard_char;
object symbol_standard_char_p;
object symbol_standard_class;
object symbol_standard_generic_function;
object symbol_standard_method;
object symbol_standard_object;
object symbol_step;
object symbol_storage_condition;
object symbol_store_value;
object symbol_stream;
object symbol_stream_element_type;
object symbol_stream_error;
object symbol_stream_error_stream;
object symbol_stream_external_format;
object symbol_streamp;
object symbol_string;
object symbol_string_capitalize;
object symbol_string_downcase;
object symbol_string_equal;
object symbol_string_greaterp;
object symbol_string_left_trim;
object symbol_string_lessp;
object symbol_string_not_equal;
object symbol_string_not_greaterp;
object symbol_string_not_lessp;
object symbol_string_right_trim;
object symbol_string_stream;
object symbol_string_trim;
object symbol_string_upcase;
object symbol_string_slash_equal;
object symbol_string_less_than_sign;
object symbol_string_less_than_or_equal_sign;
object symbol_string_equal_sign;
object symbol_string_greater_than_sign;
object symbol_string_greater_than_or_equal_sign;
object symbol_stringp;
object symbol_structure;
object symbol_structure_class;
object symbol_structure_object;
object symbol_style_warning;
object symbol_sublis;
object symbol_subseq;
object symbol_subsetp;
object symbol_subst;
object symbol_subst_if;
object symbol_subst_if_not;
object symbol_substitute;
object symbol_substitute_if;
object symbol_substitute_if_not;
object symbol_subtypep;
object symbol_svref;
object symbol_sxhash;
object symbol_symbol;
object symbol_symbol_function;
object symbol_symbol_macrolet;
object symbol_symbol_name;
object symbol_symbol_package;
object symbol_symbol_plist;
object symbol_symbol_value;
object symbol_symbolp;
object symbol_synonym_stream;
object symbol_synonym_stream_symbol;
object symbol_t;
object symbol_tagbody;
object symbol_tailp;
object symbol_tan;
object symbol_tanh;
object symbol_tenth;
object symbol_terpri;
object symbol_the;
object symbol_third;
object symbol_throw;
object symbol_time;
object symbol_trace;
object symbol_translate_logical_pathname;
object symbol_translate_pathname;
object symbol_tree_equal;
object symbol_truename;
object symbol_truncate;
object symbol_two_way_stream;
object symbol_two_way_stream_input_stream;
object symbol_two_way_stream_output_stream;
object symbol_type;
object symbol_type_error;
object symbol_type_error_datum;
object symbol_type_error_expected_type;
object symbol_type_of;
object symbol_typecase;
object symbol_typep;
object symbol_unbound_slot;
object symbol_unbound_slot_instance;
object symbol_unbound_variable;
object symbol_undefined_function;
object symbol_unexport;
object symbol_unintern;
object symbol_union;
object symbol_unless;
object symbol_unread_char;
object symbol_unsigned_byte;
object symbol_untrace;
object symbol_unuse_package;
object symbol_unwind_protect;
object symbol_update_instance_for_different_class;
object symbol_update_instance_for_redefined_class;
object symbol_upgraded_array_element_type;
object symbol_upgraded_complex_part_type;
object symbol_upper_case_p;
object symbol_use_package;
object symbol_use_value;
object symbol_user_homedir_pathname;
object symbol_values;
object symbol_values_list;
object symbol_variable;
object symbol_vector;
object symbol_vector_pop;
object symbol_vector_push;
object symbol_vector_push_extend;
object symbol_vectorp;
object symbol_warn;
object symbol_warning;
object symbol_when;
object symbol_wild_pathname_p;
object symbol_with_accessors;
object symbol_with_compilation_unit;
object symbol_with_condition_restarts;
object symbol_with_hash_table_iterator;
object symbol_with_input_from_string;
object symbol_with_open_file;
object symbol_with_open_stream;
object symbol_with_output_to_string;
object symbol_with_package_iterator;
object symbol_with_simple_restart;
object symbol_with_slots;
object symbol_with_standard_io_syntax;
object symbol_write;
object symbol_write_byte;
object symbol_write_char;
object symbol_write_line;
object symbol_write_sequence;
object symbol_write_string;
object symbol_write_to_string;
object symbol_y_or_n_p;
object symbol_yes_or_no_p;
object symbol_zerop;
object symbol_ampersand_allow_other_keys;
object symbol_ampersand_aux;
object symbol_ampersand_body;
object symbol_ampersand_environment;
object symbol_ampersand_key;
object symbol_ampersand_optional;
object symbol_ampersand_rest;
object symbol_ampersand_whole;
object symbol_star;
object symbol_star_star;
object symbol_star_star_star;
object symbol_star_break_on_signals_star;
object symbol_star_compile_file_pathname_star;
object symbol_star_compile_file_truename_star;
object symbol_star_compile_print_star;
object symbol_star_compile_verbose_star;
object symbol_star_debug_io_star;
object symbol_star_debugger_hook_star;
object symbol_star_default_pathname_defaults_star;
object symbol_star_error_output_star;
object symbol_star_features_star;
object symbol_star_gensym_counter_star;
object symbol_star_load_pathname_star;
object symbol_star_load_print_star;
object symbol_star_load_truename_star;
object symbol_star_load_verbose_star;
object symbol_star_macroexpand_hook_star;
object symbol_star_modules_star;
object symbol_star_package_star;
object symbol_star_print_array_star;
object symbol_star_print_base_star;
object symbol_star_print_case_star;
object symbol_star_print_circle_star;
object symbol_star_print_escape_star;
object symbol_star_print_gensym_star;
object symbol_star_print_length_star;
object symbol_star_print_level_star;
object symbol_star_print_lines_star;
object symbol_star_print_miser_width_star;
object symbol_star_print_pprint_dispatch_star;
object symbol_star_print_pretty_star;
object symbol_star_print_radix_star;
object symbol_star_print_readably_star;
object symbol_star_print_right_margin_star;
object symbol_star_query_io_star;
object symbol_star_random_state_star;
object symbol_star_read_base_star;
object symbol_star_read_default_float_format_star;
object symbol_star_read_eval_star;
object symbol_star_read_suppress_star;
object symbol_star_readtable_star;
object symbol_star_standard_input_star;
object symbol_star_standard_output_star;
object symbol_star_terminal_io_star;
object symbol_star_trace_output_star;
object symbol_plus;
object symbol_plus_plus;
object symbol_plus_plus_plus;
object symbol_minus;
object symbol_slash;
object symbol_slash_slash;
object symbol_slash_slash_slash;
object symbol_slash_equal;
object symbol_one_plus;
object symbol_one_minus;
object symbol_less_than_sign;
object symbol_less_than_or_equal_sign;
object symbol_equal_sign;
object symbol_greater_than_sign;
object symbol_greater_than_or_equal_sign;

object keyword_datum;
object keyword_expected_type;

object data_and_control_flow_symbol_too_few_arguments;
object data_and_control_flow_symbol_too_many_arguments;

static int symbol_initialized_p = 0;

typedef struct symbol_rack *symbol_rack;

struct symbol_rack
{
  struct rack prefix;
  object name;
  object package;
  object function;
  object setf_function;
  object macro_function;
  object compiler_macro_function;
  object value;
  object type_expander;
  object class;
  object method_combination_template;
};

static int symbol_rack_size = sizeof(struct symbol_rack);

object
c_function_symbol_name(object symbol)
{
  return ((symbol_rack) rack_of(symbol)) -> name;
}

object
c_function_symbol_package(object symbol)
{
  return ((symbol_rack) rack_of(symbol)) -> package;
}

object
symbol_slot_function(object symbol)
{
  return ((symbol_rack) rack_of(symbol)) -> function;
}

void
set_symbol_slot_function(object symbol, object function)
{
  ((symbol_rack) rack_of(symbol)) -> function = function;
}

object
c_function_symbol_slot_value(object symbol)
{
  return ((symbol_rack) rack_of(symbol)) -> value;
}

void
c_function_set_symbol_slot_value(object symbol, object value)
{
  ((symbol_rack) rack_of(symbol)) -> value = value;
}

object
make_symbol()
{
  object result = make_object();
  symbol_rack r = (symbol_rack) malloc(symbol_rack_size);
  set_class_of(result, class_symbol);
  set_rack_of(result, (rack) r);
  return result;
}

object
c_function_symbol_to_symbol(char *s, object package)
{
  object result = make_symbol();
  object name = c_function_string_to_string(s);
  symbol_rack r = (symbol_rack) rack_of(result);
  r -> name = name;
  r -> package = package;
  return result;
}

object
c_function_symbolp(object maybe_symbol)
{
  return class_of(maybe_symbol) == class_symbol ? symbol_t : symbol_nil;
}

object
make_common_lisp_symbol(char *c_name)
{
  object result = c_function_symbol_to_symbol(c_name, package_common_lisp);
  package_add_external_symbol(package_common_lisp, result);
  return result;
}

object
make_keyword_symbol(char *c_name)
{
  object result = c_function_symbol_to_symbol(c_name, package_keyword);
  package_add_external_symbol(package_common_lisp, result);
  return result;
}

void
ensure_symbol_initialized(void)
{
  if(symbol_initialized_p) return;
  ensure_package_initialized();

  symbol_abort = make_common_lisp_symbol("ABORT");
  symbol_abs = make_common_lisp_symbol("ABS");
  symbol_acons = make_common_lisp_symbol("ACONS");
  symbol_acos = make_common_lisp_symbol("ACOS");
  symbol_acosh = make_common_lisp_symbol("ACOSH");
  symbol_add_method = make_common_lisp_symbol("ADD-METHOD");
  symbol_adjoin = make_common_lisp_symbol("ADJOIN");
  symbol_adjust_array = make_common_lisp_symbol("ADJUST-ARRAY");
  symbol_adjustable_array_p = make_common_lisp_symbol("ADJUSTABLE-ARRAY-P");
  symbol_allocate_instance = make_common_lisp_symbol("ALLOCATE-INSTANCE");
  symbol_alpha_char_p = make_common_lisp_symbol("ALPHA-CHAR-P");
  symbol_alphanumericp = make_common_lisp_symbol("ALPHANUMERICP");
  symbol_and = make_common_lisp_symbol("AND");
  symbol_append = make_common_lisp_symbol("APPEND");
  symbol_apply = make_common_lisp_symbol("APPLY");
  symbol_apropos = make_common_lisp_symbol("APROPOS");
  symbol_apropos_list = make_common_lisp_symbol("APROPOS-LIST");
  symbol_aref = make_common_lisp_symbol("AREF");
  symbol_arithmetic_error = make_common_lisp_symbol("ARITHMETIC-ERROR");
  symbol_arithmetic_error_operands = make_common_lisp_symbol("ARITHMETIC-ERROR-OPERANDS");
  symbol_arithmetic_error_operation = make_common_lisp_symbol("ARITHMETIC-ERROR-OPERATION");
  symbol_array = make_common_lisp_symbol("ARRAY");
  symbol_array_dimension = make_common_lisp_symbol("ARRAY-DIMENSION");
  symbol_array_dimension_limit = make_common_lisp_symbol("ARRAY-DIMENSION-LIMIT");
  symbol_array_dimensons = make_common_lisp_symbol("ARRAY-DIMENSONS");
  symbol_array_displacement = make_common_lisp_symbol("ARRAY-DISPLACEMENT");
  symbol_array_element_type = make_common_lisp_symbol("ARRAY-ELEMENT-TYPE");
  symbol_array_has_fill_pointer_p = make_common_lisp_symbol("ARRAY-HAS-FILL-POINTER-P");
  symbol_array_in_bounds_p = make_common_lisp_symbol("ARRAY-IN-BOUNDS-P");
  symbol_array_rank = make_common_lisp_symbol("ARRAY-RANK");
  symbol_array_rank_limit = make_common_lisp_symbol("ARRAY-RANK-LIMIT");
  symbol_array_row_major_index = make_common_lisp_symbol("ARRAY-ROW-MAJOR-INDEX");
  symbol_array_total_size = make_common_lisp_symbol("ARRAY-TOTAL-SIZE");
  symbol_array_total_size_limit = make_common_lisp_symbol("ARRAY-TOTAL-SIZE-LIMIT");
  symbol_arrayp = make_common_lisp_symbol("ARRAYP");
  symbol_ash = make_common_lisp_symbol("ASH");
  symbol_asin = make_common_lisp_symbol("ASIN");
  symbol_asinh = make_common_lisp_symbol("ASINH");
  symbol_assert = make_common_lisp_symbol("ASSERT");
  symbol_assoc = make_common_lisp_symbol("ASSOC");
  symbol_assoc_if = make_common_lisp_symbol("ASSOC-IF");
  symbol_assoc_if_not = make_common_lisp_symbol("ASSOC-IF-NOT");
  symbol_atan = make_common_lisp_symbol("ATAN");
  symbol_atanh = make_common_lisp_symbol("ATANH");
  symbol_atom = make_common_lisp_symbol("ATOM");

  symbol_base_char = make_common_lisp_symbol("BASE-CHAR");
  symbol_base_string = make_common_lisp_symbol("BASE-STRING");
  symbol_bignum = make_common_lisp_symbol("BIGNUM");
  symbol_bit = make_common_lisp_symbol("BIT");
  symbol_bit_and = make_common_lisp_symbol("BIT-AND");
  symbol_bit_andc1 = make_common_lisp_symbol("BIT-ANDC1");
  symbol_bit_andc2 = make_common_lisp_symbol("BIT-ANDC2");
  symbol_bit_eqv = make_common_lisp_symbol("BIT-EQV");
  symbol_bit_ior = make_common_lisp_symbol("BIT-IOR");
  symbol_bit_nand = make_common_lisp_symbol("BIT-NAND");
  symbol_bit_nor = make_common_lisp_symbol("BIT-NOR");
  symbol_bit_not = make_common_lisp_symbol("BIT-NOT");
  symbol_bit_orc1 = make_common_lisp_symbol("BIT-ORC1");
  symbol_bit_orc2 = make_common_lisp_symbol("BIT-ORC2");
  symbol_bit_vector = make_common_lisp_symbol("BIT-VECTOR");
  symbol_bit_vector_p = make_common_lisp_symbol("BIT-VECTOR-P");
  symbol_bit_xor = make_common_lisp_symbol("BIT-XOR");
  symbol_block = make_common_lisp_symbol("BLOCK");
  symbol_boole = make_common_lisp_symbol("BOOLE");
  symbol_boole_1 = make_common_lisp_symbol("BOOLE-1");
  symbol_boole_2 = make_common_lisp_symbol("BOOLE-2");
  symbol_boole_and = make_common_lisp_symbol("BOOLE-AND");
  symbol_boole_andc1 = make_common_lisp_symbol("BOOLE-ANDC1");
  symbol_boole_andc2 = make_common_lisp_symbol("BOOLE-ANDC2");
  symbol_boole_c1 = make_common_lisp_symbol("BOOLE-C1");
  symbol_boole_c2 = make_common_lisp_symbol("BOOLE-C2");
  symbol_boole_clr = make_common_lisp_symbol("BOOLE-CLR");
  symbol_boole_eqv = make_common_lisp_symbol("BOOLE-EQV");
  symbol_boole_ior = make_common_lisp_symbol("BOOLE-IOR");
  symbol_boole_nand = make_common_lisp_symbol("BOOLE-NAND");
  symbol_boole_nor = make_common_lisp_symbol("BOOLE-NOR");
  symbol_boole_orc1 = make_common_lisp_symbol("BOOLE-ORC1");
  symbol_boole_orc2 = make_common_lisp_symbol("BOOLE-ORC2");
  symbol_boole_set = make_common_lisp_symbol("BOOLE-SET");
  symbol_boole_xor = make_common_lisp_symbol("BOOLE-XOR");
  symbol_boolean = make_common_lisp_symbol("BOOLEAN");
  symbol_both_case_p = make_common_lisp_symbol("BOTH-CASE-P");
  symbol_boundp = make_common_lisp_symbol("BOUNDP");
  symbol_break = make_common_lisp_symbol("BREAK");
  symbol_broadcast_stream = make_common_lisp_symbol("BROADCAST-STREAM");
  symbol_broadcast_stream_streams = make_common_lisp_symbol("BROADCAST-STREAM-STREAMS");
  symbol_built_in_class = make_common_lisp_symbol("BUILT-IN-CLASS");
  symbol_butlast = make_common_lisp_symbol("BUTLAST");
  symbol_byte = make_common_lisp_symbol("BYTE");
  symbol_byte_position = make_common_lisp_symbol("BYTE-POSITION");
  symbol_byte_size = make_common_lisp_symbol("BYTE-SIZE");
  
  symbol_caaaar = make_common_lisp_symbol("CAAAAR");
  symbol_caaadr = make_common_lisp_symbol("CAAADR");
  symbol_caaar = make_common_lisp_symbol("CAAAR");
  symbol_caadar = make_common_lisp_symbol("CAADAR");
  symbol_caaddr = make_common_lisp_symbol("CAADDR");
  symbol_caadr = make_common_lisp_symbol("CAADR");
  symbol_caar = make_common_lisp_symbol("CAAR");
  symbol_cadaar = make_common_lisp_symbol("CADAAR");
  symbol_cadadr = make_common_lisp_symbol("CADADR");
  symbol_cadar = make_common_lisp_symbol("CADAR");
  symbol_caddar = make_common_lisp_symbol("CADDAR");
  symbol_cadddr = make_common_lisp_symbol("CADDDR");
  symbol_caddr = make_common_lisp_symbol("CADDR");
  symbol_cadr = make_common_lisp_symbol("CADR");
  symbol_call_arguments_limit = make_common_lisp_symbol("CALL-ARGUMENTS-LIMIT");
  symbol_call_method = make_common_lisp_symbol("CALL-METHOD");
  symbol_call_next_method = make_common_lisp_symbol("CALL-NEXT-METHOD");
  symbol_car = make_common_lisp_symbol("CAR");
  symbol_case = make_common_lisp_symbol("CASE");
  symbol_catch = make_common_lisp_symbol("CATCH");
  symbol_ccase = make_common_lisp_symbol("CCASE");
  symbol_cdaaar = make_common_lisp_symbol("CDAAAR");
  symbol_cdaadr = make_common_lisp_symbol("CDAADR");
  symbol_cdaar = make_common_lisp_symbol("CDAAR");
  symbol_cdadar = make_common_lisp_symbol("CDADAR");
  symbol_cdaddr = make_common_lisp_symbol("CDADDR");
  symbol_cdadr = make_common_lisp_symbol("CDADR");
  symbol_cdar = make_common_lisp_symbol("CDAR");
  symbol_cddaar = make_common_lisp_symbol("CDDAAR");
  symbol_cddadr = make_common_lisp_symbol("CDDADR");
  symbol_cddar = make_common_lisp_symbol("CDDAR");
  symbol_cdddar = make_common_lisp_symbol("CDDDAR");
  symbol_cddddr = make_common_lisp_symbol("CDDDDR");
  symbol_cdddr = make_common_lisp_symbol("CDDDR");
  symbol_cddr = make_common_lisp_symbol("CDDR");
  symbol_cdr = make_common_lisp_symbol("CDR");
  symbol_ceiling = make_common_lisp_symbol("CEILING");
  symbol_cell_error = make_common_lisp_symbol("CELL-ERROR");
  symbol_cell_error_name = make_common_lisp_symbol("CELL-ERROR-NAME");
  symbol_cerror = make_common_lisp_symbol("CERROR");
  symbol_change_class = make_common_lisp_symbol("CHANGE-CLASS");
  symbol_char = make_common_lisp_symbol("CHAR");
  symbol_char_code = make_common_lisp_symbol("CHAR-CODE");
  symbol_char_code_limit = make_common_lisp_symbol("CHAR-CODE-LIMIT");
  symbol_char_downcase = make_common_lisp_symbol("CHAR-DOWNCASE");
  symbol_char_equal = make_common_lisp_symbol("CHAR-EQUAL");
  symbol_char_greaterp = make_common_lisp_symbol("CHAR-GREATERP");
  symbol_char_int = make_common_lisp_symbol("CHAR-INT");
  symbol_char_lessp = make_common_lisp_symbol("CHAR-LESSP");
  symbol_char_name = make_common_lisp_symbol("CHAR-NAME");
  symbol_char_not_equal = make_common_lisp_symbol("CHAR-NOT-EQUAL");
  symbol_char_not_greaterp = make_common_lisp_symbol("CHAR-NOT-GREATERP");
  symbol_char_not_lessp = make_common_lisp_symbol("CHAR-NOT-LESSP");
  symbol_char_upcase = make_common_lisp_symbol("CHAR-UPCASE");
  symbol_char_not_equal_sign = make_common_lisp_symbol("CHAR/=");
  symbol_char_less_sign = make_common_lisp_symbol("CHAR<");
  symbol_char_less_or_equal_sign = make_common_lisp_symbol("CHAR<=");
  symbol_char_equal_sign = make_common_lisp_symbol("CHAR=");
  symbol_char_greater_sign = make_common_lisp_symbol("CHAR>");
  symbol_char_greater_or_equal_sign = make_common_lisp_symbol("CHAR>=");
  symbol_character = make_common_lisp_symbol("CHARACTER");
  symbol_characterp = make_common_lisp_symbol("CHARACTERP");
  symbol_check_type = make_common_lisp_symbol("CHECK-TYPE");
  symbol_cis = make_common_lisp_symbol("CIS");
  symbol_class = make_common_lisp_symbol("CLASS");
  symbol_class_name = make_common_lisp_symbol("CLASS-NAME");
  symbol_class_of = make_common_lisp_symbol("CLASS-OF");
  symbol_clear_input = make_common_lisp_symbol("CLEAR-INPUT");
  symbol_clear_output = make_common_lisp_symbol("CLEAR-OUTPUT");
  symbol_close = make_common_lisp_symbol("CLOSE");
  symbol_clrhash = make_common_lisp_symbol("CLRHASH");
  symbol_code_char = make_common_lisp_symbol("CODE-CHAR");
  symbol_coerce = make_common_lisp_symbol("COERCE");
  symbol_compilation_speed = make_common_lisp_symbol("COMPILATION-SPEED");
  symbol_compile = make_common_lisp_symbol("COMPILE");
  symbol_compile_file = make_common_lisp_symbol("COMPILE-FILE");
  symbol_compile_file_pathname = make_common_lisp_symbol("COMPILE-FILE-PATHNAME");
  symbol_compiled_function = make_common_lisp_symbol("COMPILED-FUNCTION");
  symbol_compiled_function_p = make_common_lisp_symbol("COMPILED-FUNCTION-P");
  symbol_compiler_macro = make_common_lisp_symbol("COMPILER-MACRO");
  symbol_compiler_macro_function = make_common_lisp_symbol("COMPILER-MACRO-FUNCTION");
  symbol_complement = make_common_lisp_symbol("COMPLEMENT");
  symbol_complex = make_common_lisp_symbol("COMPLEX");
  symbol_complexp = make_common_lisp_symbol("COMPLEXP");
  symbol_compute_applicable_methods = make_common_lisp_symbol("COMPUTE-APPLICABLE-METHODS");
  symbol_compute_restarts = make_common_lisp_symbol("COMPUTE-RESTARTS");
  symbol_concatenate = make_common_lisp_symbol("CONCATENATE");
  symbol_concatenated_stream = make_common_lisp_symbol("CONCATENATED-STREAM");
  symbol_concatenated_stream_streams = make_common_lisp_symbol("CONCATENATED-STREAM-STREAMS");
  symbol_cond = make_common_lisp_symbol("COND");
  symbol_condition = make_common_lisp_symbol("CONDITION");
  symbol_conjugate = make_common_lisp_symbol("CONJUGATE");
  symbol_cons = make_common_lisp_symbol("CONS");
  symbol_consp = make_common_lisp_symbol("CONSP");
  symbol_constantly = make_common_lisp_symbol("CONSTANTLY");
  symbol_constantp = make_common_lisp_symbol("CONSTANTP");
  symbol_continue = make_common_lisp_symbol("CONTINUE");
  symbol_control_error = make_common_lisp_symbol("CONTROL-ERROR");
  symbol_copy_alist = make_common_lisp_symbol("COPY-ALIST");
  symbol_copy_list = make_common_lisp_symbol("COPY-LIST");
  symbol_copy_pprint_dispatch = make_common_lisp_symbol("COPY-PPRINT-DISPATCH");
  symbol_copy_readtable = make_common_lisp_symbol("COPY-READTABLE");
  symbol_copy_seq = make_common_lisp_symbol("COPY-SEQ");
  symbol_copy_structure = make_common_lisp_symbol("COPY-STRUCTURE");
  symbol_copy_symbol = make_common_lisp_symbol("COPY-SYMBOL");
  symbol_copy_tree = make_common_lisp_symbol("COPY-TREE");
  symbol_cos = make_common_lisp_symbol("COS");
  symbol_cosh = make_common_lisp_symbol("COSH");
  symbol_count = make_common_lisp_symbol("COUNT");
  symbol_count_if = make_common_lisp_symbol("COUNT-IF");
  symbol_count_if_not = make_common_lisp_symbol("COUNT-IF-NOT");
  symbol_ctypecase = make_common_lisp_symbol("CTYPECASE");
  
  symbol_debug = make_common_lisp_symbol("DEBUG");
  symbol_decf = make_common_lisp_symbol("DECF");
  symbol_declaim = make_common_lisp_symbol("DECLAIM");
  symbol_declaration = make_common_lisp_symbol("DECLARATION");
  symbol_declare = make_common_lisp_symbol("DECLARE");
  symbol_decode_float = make_common_lisp_symbol("DECODE-FLOAT");
  symbol_decode_universal_time = make_common_lisp_symbol("DECODE-UNIVERSAL-TIME");
  symbol_defclass = make_common_lisp_symbol("DEFCLASS");
  symbol_defconstant = make_common_lisp_symbol("DEFCONSTANT");
  symbol_defgeneric = make_common_lisp_symbol("DEFGENERIC");
  symbol_define_compiler_macro = make_common_lisp_symbol("DEFINE-COMPILER-MACRO");
  symbol_define_condition = make_common_lisp_symbol("DEFINE-CONDITION");
  symbol_define_method_combination = make_common_lisp_symbol("DEFINE-METHOD-COMBINATION");
  symbol_define_modify_macro = make_common_lisp_symbol("DEFINE-MODIFY-MACRO");
  symbol_define_setf_expander = make_common_lisp_symbol("DEFINE-SETF-EXPANDER");
  symbol_define_symbol_macro = make_common_lisp_symbol("DEFINE-SYMBOL-MACRO");
  symbol_defmacro = make_common_lisp_symbol("DEFMACRO");
  symbol_defmethod = make_common_lisp_symbol("DEFMETHOD");
  symbol_defpackage = make_common_lisp_symbol("DEFPACKAGE");
  symbol_defparameter = make_common_lisp_symbol("DEFPARAMETER");
  symbol_defsetf = make_common_lisp_symbol("DEFSETF");
  symbol_defstruct = make_common_lisp_symbol("DEFSTRUCT");
  symbol_deftype = make_common_lisp_symbol("DEFTYPE");
  symbol_defun = make_common_lisp_symbol("DEFUN");
  symbol_defvar = make_common_lisp_symbol("DEFVAR");
  symbol_delete = make_common_lisp_symbol("DELETE");
  symbol_delete_duplicates = make_common_lisp_symbol("DELETE-DUPLICATES");
  symbol_delete_file = make_common_lisp_symbol("DELETE-FILE");
  symbol_delete_if = make_common_lisp_symbol("DELETE-IF");
  symbol_delete_if_not = make_common_lisp_symbol("DELETE-IF-NOT");
  symbol_delete_package = make_common_lisp_symbol("DELETE-PACKAGE");
  symbol_denominator = make_common_lisp_symbol("DENOMINATOR");
  symbol_deposit_field = make_common_lisp_symbol("DEPOSIT-FIELD");
  symbol_describe = make_common_lisp_symbol("DESCRIBE");
  symbol_describe_object = make_common_lisp_symbol("DESCRIBE-OBJECT");
  symbol_destructuring_bind = make_common_lisp_symbol("DESTRUCTURING-BIND");
  symbol_digit_char = make_common_lisp_symbol("DIGIT-CHAR");
  symbol_digit_char_p = make_common_lisp_symbol("DIGIT-CHAR-P");
  symbol_directory = make_common_lisp_symbol("DIRECTORY");
  symbol_directory_namestring = make_common_lisp_symbol("DIRECTORY-NAMESTRING");
  symbol_disassemble = make_common_lisp_symbol("DISASSEMBLE");
  symbol_division_by_zero = make_common_lisp_symbol("DIVISION-BY-ZERO");
  symbol_do = make_common_lisp_symbol("DO");
  symbol_do_star = make_common_lisp_symbol("DO*");
  symbol_do_all_symbols = make_common_lisp_symbol("DO-ALL-SYMBOLS");
  symbol_do_external_symbols = make_common_lisp_symbol("DO-EXTERNAL-SYMBOLS");
  symbol_do_symbols = make_common_lisp_symbol("DO-SYMBOLS");
  symbol_documentation = make_common_lisp_symbol("DOCUMENTATION");
  symbol_dolist = make_common_lisp_symbol("DOLIST");
  symbol_dotimes = make_common_lisp_symbol("DOTIMES");
  symbol_double_float = make_common_lisp_symbol("DOUBLE-FLOAT");
  symbol_double_float_epsilon = make_common_lisp_symbol("DOUBLE-FLOAT-EPSILON");
  symbol_double_float_negative_epsilon = make_common_lisp_symbol("DOUBLE-FLOAT-NEGATIVE-EPSILON");
  symbol_dpb = make_common_lisp_symbol("DPB");
  symbol_dribble = make_common_lisp_symbol("DRIBBLE");
  symbol_dynamic_extent = make_common_lisp_symbol("DYNAMIC-EXTENT");

  symbol_ecase = make_common_lisp_symbol("ECASE");
  symbol_echo_stream = make_common_lisp_symbol("ECHO-STREAM");
  symbol_echo_stream_input_stream = make_common_lisp_symbol("ECHO-STREAM-INPUT-STREAM");
  symbol_echo_stream_output_stream = make_common_lisp_symbol("ECHO-STREAM-OUTPUT-STREAM");
  symbol_ed = make_common_lisp_symbol("ED");
  symbol_eighth = make_common_lisp_symbol("EIGHTH");
  symbol_elt = make_common_lisp_symbol("ELT");
  symbol_encode_universal_time = make_common_lisp_symbol("ENCODE-UNIVERSAL-TIME");
  symbol_end_of_file = make_common_lisp_symbol("END-OF-FILE");
  symbol_endp = make_common_lisp_symbol("ENDP");
  symbol_enough_namestring = make_common_lisp_symbol("ENOUGH-NAMESTRING");
  symbol_ensure_directories_exist = make_common_lisp_symbol("ENSURE-DIRECTORIES-EXIST");
  symbol_ensure_generic_function = make_common_lisp_symbol("ENSURE-GENERIC-FUNCTION");
  symbol_eq = make_common_lisp_symbol("EQ");
  symbol_eql = make_common_lisp_symbol("EQL");
  symbol_equal = make_common_lisp_symbol("EQUAL");
  symbol_equalp = make_common_lisp_symbol("EQUALP");
  symbol_error = make_common_lisp_symbol("ERROR");
  symbol_etypecase = make_common_lisp_symbol("ETYPECASE");
  symbol_eval = make_common_lisp_symbol("EVAL");
  symbol_eval_when = make_common_lisp_symbol("EVAL-WHEN");
  symbol_evenp = make_common_lisp_symbol("EVENP");
  symbol_every = make_common_lisp_symbol("EVERY");
  symbol_exp = make_common_lisp_symbol("EXP");
  symbol_export = make_common_lisp_symbol("EXPORT");
  symbol_expt = make_common_lisp_symbol("EXPT");
  symbol_extended_char = make_common_lisp_symbol("EXTENDED-CHAR");

  symbol_fboundp = make_common_lisp_symbol("FBOUNDP");
  symbol_fceiling = make_common_lisp_symbol("FCEILING");
  symbol_fdefinition = make_common_lisp_symbol("FDEFINITION");
  symbol_ffloor = make_common_lisp_symbol("FFLOOR");
  symbol_fifth = make_common_lisp_symbol("FIFTH");
  symbol_file_author = make_common_lisp_symbol("FILE-AUTHOR");
  symbol_file_error = make_common_lisp_symbol("FILE-ERROR");
  symbol_file_error_pathname = make_common_lisp_symbol("FILE-ERROR-PATHNAME");
  symbol_file_length = make_common_lisp_symbol("FILE-LENGTH");
  symbol_file_namestring = make_common_lisp_symbol("FILE-NAMESTRING");
  symbol_file_position = make_common_lisp_symbol("FILE-POSITION");
  symbol_file_stream = make_common_lisp_symbol("FILE-STREAM");
  symbol_file_string_length = make_common_lisp_symbol("FILE-STRING-LENGTH");
  symbol_file_write_date = make_common_lisp_symbol("FILE-WRITE-DATE");
  symbol_fill = make_common_lisp_symbol("FILL");
  symbol_fill_pointer = make_common_lisp_symbol("FILL-POINTER");
  symbol_find = make_common_lisp_symbol("FIND");
  symbol_find_all_symbols = make_common_lisp_symbol("FIND-ALL-SYMBOLS");
  symbol_find_class = make_common_lisp_symbol("FIND-CLASS");
  symbol_find_if = make_common_lisp_symbol("FIND-IF");
  symbol_find_if_not = make_common_lisp_symbol("FIND-IF-NOT");
  symbol_find_method = make_common_lisp_symbol("FIND-METHOD");
  symbol_find_package = make_common_lisp_symbol("FIND-PACKAGE");
  symbol_find_restart = make_common_lisp_symbol("FIND-RESTART");
  symbol_find_symbol = make_common_lisp_symbol("FIND-SYMBOL");
  symbol_finish_output = make_common_lisp_symbol("FINISH-OUTPUT");
  symbol_first = make_common_lisp_symbol("FIRST");
  symbol_fixnum = make_common_lisp_symbol("FIXNUM");
  symbol_flet = make_common_lisp_symbol("FLET");
  symbol_float = make_common_lisp_symbol("FLOAT");
  symbol_float_digits = make_common_lisp_symbol("FLOAT-DIGITS");
  symbol_float_precision = make_common_lisp_symbol("FLOAT-PRECISION");
  symbol_float_radix = make_common_lisp_symbol("FLOAT-RADIX");
  symbol_float_sign = make_common_lisp_symbol("FLOAT-SIGN");
  symbol_floating_point_inexact = make_common_lisp_symbol("FLOATING-POINT-INEXACT");
  symbol_floating_point_invalid_operation = make_common_lisp_symbol("FLOATING-POINT-INVALID-OPERATION");
  symbol_floating_point_overflow = make_common_lisp_symbol("FLOATING-POINT-OVERFLOW");
  symbol_floating_point_underflow = make_common_lisp_symbol("FLOATING-POINT-UNDERFLOW");
  symbol_floatp = make_common_lisp_symbol("FLOATP");
  symbol_floor = make_common_lisp_symbol("FLOOR");
  symbol_fmakunbound = make_common_lisp_symbol("FMAKUNBOUND");
  symbol_force_output = make_common_lisp_symbol("FORCE-OUTPUT");
  symbol_format = make_common_lisp_symbol("FORMAT");
  symbol_formatter = make_common_lisp_symbol("FORMATTER");
  symbol_fourth = make_common_lisp_symbol("FOURTH");
  symbol_fresh_line = make_common_lisp_symbol("FRESH-LINE");
  symbol_fround = make_common_lisp_symbol("FROUND");
  symbol_ftruncate = make_common_lisp_symbol("FTRUNCATE");
  symbol_ftype = make_common_lisp_symbol("FTYPE");
  symbol_funcall = make_common_lisp_symbol("FUNCALL");
  symbol_function = make_common_lisp_symbol("FUNCTION");
  symbol_function_keywords = make_common_lisp_symbol("FUNCTION-KEYWORDS");
  symbol_function_lambda_expression = make_common_lisp_symbol("FUNCTION-LAMBDA-EXPRESSION");
  symbol_functionp = make_common_lisp_symbol("FUNCTIONP");

  symbol_gcd = make_common_lisp_symbol("GCD");
  symbol_generic_function = make_common_lisp_symbol("GENERIC-FUNCTION");
  symbol_gensym = make_common_lisp_symbol("GENSYM");
  symbol_gentemp = make_common_lisp_symbol("GENTEMP");
  symbol_get = make_common_lisp_symbol("GET");
  symbol_get_decoded_time = make_common_lisp_symbol("GET-DECODED-TIME");
  symbol_get_dispatch_macro_character = make_common_lisp_symbol("GET-DISPATCH-MACRO-CHARACTER");
  symbol_get_internal_real_time = make_common_lisp_symbol("GET-INTERNAL-REAL-TIME");
  symbol_get_internal_run_time = make_common_lisp_symbol("GET-INTERNAL-RUN-TIME");
  symbol_get_macro_character = make_common_lisp_symbol("GET-MACRO-CHARACTER");
  symbol_get_output_stream_string = make_common_lisp_symbol("GET-OUTPUT-STREAM-STRING");
  symbol_get_properties = make_common_lisp_symbol("GET-PROPERTIES");
  symbol_get_setf_expansion = make_common_lisp_symbol("GET-SETF-EXPANSION");
  symbol_get_universal_time = make_common_lisp_symbol("GET-UNIVERSAL-TIME");
  symbol_getf = make_common_lisp_symbol("GETF");
  symbol_gethash = make_common_lisp_symbol("GETHASH");
  symbol_go = make_common_lisp_symbol("GO");
  symbol_graphic_char_p = make_common_lisp_symbol("GRAPHIC-CHAR-P");

  symbol_handler_bind = make_common_lisp_symbol("HANDLER-BIND");
  symbol_handler_case = make_common_lisp_symbol("HANDLER-CASE");
  symbol_hash_table = make_common_lisp_symbol("HASH-TABLE");
  symbol_hash_table_count = make_common_lisp_symbol("HASH-TABLE-COUNT");
  symbol_hash_table_p = make_common_lisp_symbol("HASH-TABLE-P");
  symbol_hash_table_rehash_size = make_common_lisp_symbol("HASH-TABLE-REHASH-SIZE");
  symbol_hash_table_rehash_threshold = make_common_lisp_symbol("HASH-TABLE-REHASH-THRESHOLD");
  symbol_hash_table_size = make_common_lisp_symbol("HASH-TABLE-SIZE");
  symbol_hash_table_test = make_common_lisp_symbol("HASH-TABLE-TEST");
  symbol_host_namestring = make_common_lisp_symbol("HOST-NAMESTRING");

  symbol_identity = make_common_lisp_symbol("IDENTITY");
  symbol_if = make_common_lisp_symbol("IF");
  symbol_ignorable = make_common_lisp_symbol("IGNORABLE");
  symbol_ignore = make_common_lisp_symbol("IGNORE");
  symbol_ignore_errors = make_common_lisp_symbol("IGNORE-ERRORS");
  symbol_imagpart = make_common_lisp_symbol("IMAGPART");
  symbol_import = make_common_lisp_symbol("IMPORT");
  symbol_in_package = make_common_lisp_symbol("IN-PACKAGE");
  symbol_incf = make_common_lisp_symbol("INCF");
  symbol_initialize_instance = make_common_lisp_symbol("INITIALIZE-INSTANCE");
  symbol_inline = make_common_lisp_symbol("INLINE");
  symbol_input_stream_p = make_common_lisp_symbol("INPUT-STREAM-P");
  symbol_inspect = make_common_lisp_symbol("INSPECT");
  symbol_integer = make_common_lisp_symbol("INTEGER");
  symbol_integer_decode_float = make_common_lisp_symbol("INTEGER-DECODE-FLOAT");
  symbol_integer_length = make_common_lisp_symbol("INTEGER-LENGTH");
  symbol_integerp = make_common_lisp_symbol("INTEGERP");
  symbol_interactive_stream_p = make_common_lisp_symbol("INTERACTIVE-STREAM-P");
  symbol_intern = make_common_lisp_symbol("INTERN");
  symbol_internal_time_units_per_second = make_common_lisp_symbol("INTERNAL-TIME-UNITS-PER-SECOND");
  symbol_intersection = make_common_lisp_symbol("INTERSECTION");
  symbol_invalid_method_error = make_common_lisp_symbol("INVALID-METHOD-ERROR");
  symbol_invoke_debugger = make_common_lisp_symbol("INVOKE-DEBUGGER");
  symbol_invoke_restart = make_common_lisp_symbol("INVOKE-RESTART");
  symbol_invoke_restart_interactively = make_common_lisp_symbol("INVOKE-RESTART-INTERACTIVELY");
  symbol_isqrt = make_common_lisp_symbol("ISQRT");

  symbol_keyword = make_common_lisp_symbol("KEYWORD");
  symbol_keywordp = make_common_lisp_symbol("KEYWORDP");

  symbol_labels = make_common_lisp_symbol("LABELS");
  symbol_lambda = make_common_lisp_symbol("LAMBDA");
  symbol_lambda_list_keywords = make_common_lisp_symbol("LAMBDA-LIST-KEYWORDS");
  symbol_lambda_parameters_limit = make_common_lisp_symbol("LAMBDA-PARAMETERS-LIMIT");
  symbol_last = make_common_lisp_symbol("LAST");
  symbol_lcm = make_common_lisp_symbol("LCM");
  symbol_ldb = make_common_lisp_symbol("LDB");
  symbol_ldb_test = make_common_lisp_symbol("LDB-TEST");
  symbol_ldiff = make_common_lisp_symbol("LDIFF");
  symbol_least_negative_double_float = make_common_lisp_symbol("LEAST-NEGATIVE-DOUBLE-FLOAT");
  symbol_least_negative_long_float = make_common_lisp_symbol("LEAST-NEGATIVE-LONG-FLOAT");
  symbol_least_negative_normalized_double_float = make_common_lisp_symbol("LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT");
  symbol_least_negative_normalized_long_float = make_common_lisp_symbol("LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT");
  symbol_least_negative_normalized_short_float = make_common_lisp_symbol("LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT");
  symbol_least_negative_normalized_single_float = make_common_lisp_symbol("LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT");
  symbol_least_negative_short_float = make_common_lisp_symbol("LEAST-NEGATIVE-SHORT-FLOAT");
  symbol_least_negative_single_float = make_common_lisp_symbol("LEAST-NEGATIVE-SINGLE-FLOAT");
  symbol_least_positive_double_float = make_common_lisp_symbol("LEAST-POSITIVE-DOUBLE-FLOAT");
  symbol_least_positive_long_float = make_common_lisp_symbol("LEAST-POSITIVE-LONG-FLOAT");
  symbol_least_positive_normalized_double_float = make_common_lisp_symbol("LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT");
  symbol_least_positive_normalized_long_float = make_common_lisp_symbol("LEAST-POSITIVE-NORMALIZED-LONG-FLOAT");
  symbol_least_positive_normalized_short_float = make_common_lisp_symbol("LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT");
  symbol_least_positive_normalized_single_float = make_common_lisp_symbol("LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT");
  symbol_least_positive_short_float = make_common_lisp_symbol("LEAST-POSITIVE-SHORT-FLOAT");
  symbol_least_positive_single_float = make_common_lisp_symbol("LEAST-POSITIVE-SINGLE-FLOAT");
  symbol_length = make_common_lisp_symbol("LENGTH");
  symbol_let = make_common_lisp_symbol("LET");
  symbol_let_star = make_common_lisp_symbol("LET*");
  symbol_lisp_implementation_type = make_common_lisp_symbol("LISP-IMPLEMENTATION-TYPE");
  symbol_lisp_implementation_version = make_common_lisp_symbol("LISP-IMPLEMENTATION-VERSION");
  symbol_list = make_common_lisp_symbol("LIST");
  symbol_list_star = make_common_lisp_symbol("LIST*");
  symbol_list_all_packages = make_common_lisp_symbol("LIST-ALL-PACKAGES");
  symbol_list_length = make_common_lisp_symbol("LIST-LENGTH");
  symbol_listen = make_common_lisp_symbol("LISTEN");
  symbol_listp = make_common_lisp_symbol("LISTP");
  symbol_load = make_common_lisp_symbol("LOAD");
  symbol_load_logical_pathname_translations = make_common_lisp_symbol("LOAD-LOGICAL-PATHNAME-TRANSLATIONS");
  symbol_load_time_value = make_common_lisp_symbol("LOAD-TIME-VALUE");
  symbol_locally = make_common_lisp_symbol("LOCALLY");
  symbol_log = make_common_lisp_symbol("LOG");
  symbol_logand = make_common_lisp_symbol("LOGAND");
  symbol_logandc1 = make_common_lisp_symbol("LOGANDC1");
  symbol_logandc2 = make_common_lisp_symbol("LOGANDC2");
  symbol_logbitp = make_common_lisp_symbol("LOGBITP");
  symbol_logcount = make_common_lisp_symbol("LOGCOUNT");
  symbol_logeqv = make_common_lisp_symbol("LOGEQV");
  symbol_logical_pathname = make_common_lisp_symbol("LOGICAL-PATHNAME");
  symbol_logical_pathname_translations = make_common_lisp_symbol("LOGICAL-PATHNAME-TRANSLATIONS");
  symbol_logior = make_common_lisp_symbol("LOGIOR");
  symbol_lognand = make_common_lisp_symbol("LOGNAND");
  symbol_lognor = make_common_lisp_symbol("LOGNOR");
  symbol_lognot = make_common_lisp_symbol("LOGNOT");
  symbol_logorc1 = make_common_lisp_symbol("LOGORC1");
  symbol_logorc2 = make_common_lisp_symbol("LOGORC2");
  symbol_logtest = make_common_lisp_symbol("LOGTEST");
  symbol_logxor = make_common_lisp_symbol("LOGXOR");
  symbol_long_float = make_common_lisp_symbol("LONG-FLOAT");
  symbol_long_float_epsilon = make_common_lisp_symbol("LONG-FLOAT-EPSILON");
  symbol_long_float_negative_epsilon = make_common_lisp_symbol("LONG-FLOAT-NEGATIVE-EPSILON");
  symbol_long_site_name = make_common_lisp_symbol("LONG-SITE-NAME");
  symbol_loop = make_common_lisp_symbol("LOOP");
  symbol_loop_finish = make_common_lisp_symbol("LOOP-FINISH");
  symbol_lower_case_p = make_common_lisp_symbol("LOWER-CASE-P");

  symbol_machine_instance = make_common_lisp_symbol("MACHINE-INSTANCE");
  symbol_machine_type = make_common_lisp_symbol("MACHINE-TYPE");
  symbol_machine_version = make_common_lisp_symbol("MACHINE-VERSION");
  symbol_macro_function = make_common_lisp_symbol("MACRO-FUNCTION");
  symbol_macroexpand = make_common_lisp_symbol("MACROEXPAND");
  symbol_macroexpand_1 = make_common_lisp_symbol("MACROEXPAND-1");
  symbol_macrolet = make_common_lisp_symbol("MACROLET");
  symbol_make_array = make_common_lisp_symbol("MAKE-ARRAY");
  symbol_make_broadcast_stream = make_common_lisp_symbol("MAKE-BROADCAST-STREAM");
  symbol_make_concatenated_stream = make_common_lisp_symbol("MAKE-CONCATENATED-STREAM");
  symbol_make_condition = make_common_lisp_symbol("MAKE-CONDITION");
  symbol_make_dispatch_macro_character = make_common_lisp_symbol("MAKE-DISPATCH-MACRO-CHARACTER");
  symbol_make_echo_stream = make_common_lisp_symbol("MAKE-ECHO-STREAM");
  symbol_make_hash_table = make_common_lisp_symbol("MAKE-HASH-TABLE");
  symbol_make_instance = make_common_lisp_symbol("MAKE-INSTANCE");
  symbol_make_instances_obsolete = make_common_lisp_symbol("MAKE-INSTANCES-OBSOLETE");
  symbol_make_list = make_common_lisp_symbol("MAKE-LIST");
  symbol_make_load_form = make_common_lisp_symbol("MAKE-LOAD-FORM");
  symbol_make_load_form_saving_slots = make_common_lisp_symbol("MAKE-LOAD-FORM-SAVING-SLOTS");
  symbol_make_method = make_common_lisp_symbol("MAKE-METHOD");
  symbol_make_package = make_common_lisp_symbol("MAKE-PACKAGE");
  symbol_make_pathname = make_common_lisp_symbol("MAKE-PATHNAME");
  symbol_make_random_state = make_common_lisp_symbol("MAKE-RANDOM-STATE");
  symbol_make_sequence = make_common_lisp_symbol("MAKE-SEQUENCE");
  symbol_make_string = make_common_lisp_symbol("MAKE-STRING");
  symbol_make_string_input_stream = make_common_lisp_symbol("MAKE-STRING-INPUT-STREAM");
  symbol_make_string_output_stream = make_common_lisp_symbol("MAKE-STRING-OUTPUT-STREAM");
  symbol_make_symbol = make_common_lisp_symbol("MAKE-SYMBOL");
  symbol_make_synonym_stream = make_common_lisp_symbol("MAKE-SYNONYM-STREAM");
  symbol_make_two_way_stream = make_common_lisp_symbol("MAKE-TWO-WAY-STREAM");
  symbol_makunbound = make_common_lisp_symbol("MAKUNBOUND");
  symbol_map = make_common_lisp_symbol("MAP");
  symbol_map_into = make_common_lisp_symbol("MAP-INTO");
  symbol_mapc = make_common_lisp_symbol("MAPC");
  symbol_mapcan = make_common_lisp_symbol("MAPCAN");
  symbol_mapcar = make_common_lisp_symbol("MAPCAR");
  symbol_mapcon = make_common_lisp_symbol("MAPCON");
  symbol_maphash = make_common_lisp_symbol("MAPHASH");
  symbol_mapl = make_common_lisp_symbol("MAPL");
  symbol_maplist = make_common_lisp_symbol("MAPLIST");
  symbol_mask_field = make_common_lisp_symbol("MASK-FIELD");
  symbol_max = make_common_lisp_symbol("MAX");
  symbol_member = make_common_lisp_symbol("MEMBER");
  symbol_member_if = make_common_lisp_symbol("MEMBER-IF");
  symbol_member_if_not = make_common_lisp_symbol("MEMBER-IF-NOT");
  symbol_merge = make_common_lisp_symbol("MERGE");
  symbol_merge_pathnames = make_common_lisp_symbol("MERGE-PATHNAMES");
  symbol_method = make_common_lisp_symbol("METHOD");
  symbol_method_combination = make_common_lisp_symbol("METHOD-COMBINATION");
  symbol_method_combination_error = make_common_lisp_symbol("METHOD-COMBINATION-ERROR");
  symbol_method_qualifiers = make_common_lisp_symbol("METHOD-QUALIFIERS");
  symbol_min = make_common_lisp_symbol("MIN");
  symbol_minusp = make_common_lisp_symbol("MINUSP");
  symbol_mismatch = make_common_lisp_symbol("MISMATCH");
  symbol_mod = make_common_lisp_symbol("MOD");
  symbol_most_negative_double_float = make_common_lisp_symbol("MOST-NEGATIVE-DOUBLE-FLOAT");
  symbol_most_negative_fixnum = make_common_lisp_symbol("MOST-NEGATIVE-FIXNUM");
  symbol_most_negative_long_float = make_common_lisp_symbol("MOST-NEGATIVE-LONG-FLOAT");
  symbol_most_negative_short_float = make_common_lisp_symbol("MOST-NEGATIVE-SHORT-FLOAT");
  symbol_most_negative_single_float = make_common_lisp_symbol("MOST-NEGATIVE-SINGLE-FLOAT");
  symbol_most_positive_double_float = make_common_lisp_symbol("MOST-POSITIVE-DOUBLE-FLOAT");
  symbol_most_positive_fixnum = make_common_lisp_symbol("MOST-POSITIVE-FIXNUM");
  symbol_most_positive_long_float = make_common_lisp_symbol("MOST-POSITIVE-LONG-FLOAT");
  symbol_most_positive_short_float = make_common_lisp_symbol("MOST-POSITIVE-SHORT-FLOAT");
  symbol_most_positive_single_float = make_common_lisp_symbol("MOST-POSITIVE-SINGLE-FLOAT");
  symbol_muffle_warning = make_common_lisp_symbol("MUFFLE-WARNING");
  symbol_multiple_value_bind = make_common_lisp_symbol("MULTIPLE-VALUE-BIND");
  symbol_multiple_value_call = make_common_lisp_symbol("MULTIPLE-VALUE-CALL");
  symbol_multiple_value_list = make_common_lisp_symbol("MULTIPLE-VALUE-LIST");
  symbol_multiple_value_prog1 = make_common_lisp_symbol("MULTIPLE-VALUE-PROG1");
  symbol_multiple_value_setq = make_common_lisp_symbol("MULTIPLE-VALUE-SETQ");
  symbol_multiple_values_limit = make_common_lisp_symbol("MULTIPLE-VALUES-LIMIT");

  symbol_name_char = make_common_lisp_symbol("NAME-CHAR");
  symbol_namestring = make_common_lisp_symbol("NAMESTRING");
  symbol_nbutlast = make_common_lisp_symbol("NBUTLAST");
  symbol_nconc = make_common_lisp_symbol("NCONC");
  symbol_next_method_p = make_common_lisp_symbol("NEXT-METHOD-P");
  symbol_nil = make_common_lisp_symbol("NIL");
  symbol_nintersection = make_common_lisp_symbol("NINTERSECTION");
  symbol_ninth = make_common_lisp_symbol("NINTH");
  symbol_no_applicable_method = make_common_lisp_symbol("NO-APPLICABLE-METHOD");
  symbol_no_next_method = make_common_lisp_symbol("NO-NEXT-METHOD");
  symbol_not = make_common_lisp_symbol("NOT");
  symbol_notany = make_common_lisp_symbol("NOTANY");
  symbol_notevery = make_common_lisp_symbol("NOTEVERY");
  symbol_notinline = make_common_lisp_symbol("NOTINLINE");
  symbol_nreconc = make_common_lisp_symbol("NRECONC");
  symbol_nreverse = make_common_lisp_symbol("NREVERSE");
  symbol_nset_difference = make_common_lisp_symbol("NSET-DIFFERENCE");
  symbol_nset_exclusive_or = make_common_lisp_symbol("NSET-EXCLUSIVE-OR");
  symbol_nstring_capitalize = make_common_lisp_symbol("NSTRING-CAPITALIZE");
  symbol_nstring_downcase = make_common_lisp_symbol("NSTRING-DOWNCASE");
  symbol_nstring_upcase = make_common_lisp_symbol("NSTRING-UPCASE");
  symbol_nsublis = make_common_lisp_symbol("NSUBLIS");
  symbol_nsubst = make_common_lisp_symbol("NSUBST");
  symbol_nsubst_if = make_common_lisp_symbol("NSUBST-IF");
  symbol_nsubst_if_not = make_common_lisp_symbol("NSUBST-IF-NOT");
  symbol_nsubstitute = make_common_lisp_symbol("NSUBSTITUTE");
  symbol_nsubstitute_if = make_common_lisp_symbol("NSUBSTITUTE-IF");
  symbol_nsubstitute_if_not = make_common_lisp_symbol("NSUBSTITUTE-IF-NOT");
  symbol_nth = make_common_lisp_symbol("NTH");
  symbol_nth_value = make_common_lisp_symbol("NTH-VALUE");
  symbol_nthcdr = make_common_lisp_symbol("NTHCDR");
  symbol_null = make_common_lisp_symbol("NULL");
  symbol_number = make_common_lisp_symbol("NUMBER");
  symbol_numberp = make_common_lisp_symbol("NUMBERP");
  symbol_numerator = make_common_lisp_symbol("NUMERATOR");
  symbol_nunion = make_common_lisp_symbol("NUNION");
  symbol_oddp = make_common_lisp_symbol("ODDP");
  symbol_open = make_common_lisp_symbol("OPEN");
  symbol_open_stream_p = make_common_lisp_symbol("OPEN-STREAM-P");
  symbol_optimize = make_common_lisp_symbol("OPTIMIZE");
  symbol_or = make_common_lisp_symbol("OR");
  symbol_otherwise = make_common_lisp_symbol("OTHERWISE");
  symbol_output_stream_p = make_common_lisp_symbol("OUTPUT-STREAM-P");
  symbol_package = make_common_lisp_symbol("PACKAGE");
  symbol_package_error = make_common_lisp_symbol("PACKAGE-ERROR");
  symbol_package_error_package = make_common_lisp_symbol("PACKAGE-ERROR-PACKAGE");
  symbol_package_name = make_common_lisp_symbol("PACKAGE-NAME");
  symbol_package_nicknames = make_common_lisp_symbol("PACKAGE-NICKNAMES");
  symbol_package_shadowing_symbols = make_common_lisp_symbol("PACKAGE-SHADOWING-SYMBOLS");
  symbol_package_use_list = make_common_lisp_symbol("PACKAGE-USE-LIST");
  symbol_package_used_by_list = make_common_lisp_symbol("PACKAGE-USED-BY-LIST");
  symbol_packagep = make_common_lisp_symbol("PACKAGEP");
  symbol_pairlis = make_common_lisp_symbol("PAIRLIS");
  symbol_parse_error = make_common_lisp_symbol("PARSE-ERROR");
  symbol_parse_integer = make_common_lisp_symbol("PARSE-INTEGER");
  symbol_parse_namestring = make_common_lisp_symbol("PARSE-NAMESTRING");
  symbol_pathname = make_common_lisp_symbol("PATHNAME");
  symbol_pathname_device = make_common_lisp_symbol("PATHNAME-DEVICE");
  symbol_pathname_directory = make_common_lisp_symbol("PATHNAME-DIRECTORY");
  symbol_pathname_host = make_common_lisp_symbol("PATHNAME-HOST");
  symbol_pathname_match_p = make_common_lisp_symbol("PATHNAME-MATCH-P");
  symbol_pathname_name = make_common_lisp_symbol("PATHNAME-NAME");
  symbol_pathname_type = make_common_lisp_symbol("PATHNAME-TYPE");
  symbol_pathname_version = make_common_lisp_symbol("PATHNAME-VERSION");
  symbol_pathnamep = make_common_lisp_symbol("PATHNAMEP");
  symbol_peek_char = make_common_lisp_symbol("PEEK-CHAR");
  symbol_phase = make_common_lisp_symbol("PHASE");
  symbol_pi = make_common_lisp_symbol("PI");
  symbol_plusp = make_common_lisp_symbol("PLUSP");
  symbol_pop = make_common_lisp_symbol("POP");
  symbol_position = make_common_lisp_symbol("POSITION");
  symbol_position_if = make_common_lisp_symbol("POSITION-IF");
  symbol_position_if_not = make_common_lisp_symbol("POSITION-IF-NOT");
  symbol_pprint = make_common_lisp_symbol("PPRINT");
  symbol_pprint_dispatch = make_common_lisp_symbol("PPRINT-DISPATCH");
  symbol_pprint_exit_if_list_exhausted = make_common_lisp_symbol("PPRINT-EXIT-IF-LIST-EXHAUSTED");
  symbol_pprint_fill = make_common_lisp_symbol("PPRINT-FILL");
  symbol_pprint_indent = make_common_lisp_symbol("PPRINT-INDENT");
  symbol_pprint_linear = make_common_lisp_symbol("PPRINT-LINEAR");
  symbol_pprint_logical_block = make_common_lisp_symbol("PPRINT-LOGICAL-BLOCK");
  symbol_pprint_newline = make_common_lisp_symbol("PPRINT-NEWLINE");
  symbol_pprint_pop = make_common_lisp_symbol("PPRINT-POP");
  symbol_pprint_tab = make_common_lisp_symbol("PPRINT-TAB");
  symbol_pprint_tabular = make_common_lisp_symbol("PPRINT-TABULAR");
  symbol_prin1 = make_common_lisp_symbol("PRIN1");
  symbol_prin1_to_string = make_common_lisp_symbol("PRIN1-TO-STRING");
  symbol_princ = make_common_lisp_symbol("PRINC");
  symbol_princ_to_string = make_common_lisp_symbol("PRINC-TO-STRING");
  symbol_print = make_common_lisp_symbol("PRINT");
  symbol_print_not_readable = make_common_lisp_symbol("PRINT-NOT-READABLE");
  symbol_print_not_readable_object = make_common_lisp_symbol("PRINT-NOT-READABLE-OBJECT");
  symbol_print_object = make_common_lisp_symbol("PRINT-OBJECT");
  symbol_print_unreadable_object = make_common_lisp_symbol("PRINT-UNREADABLE-OBJECT");
  symbol_probe_file = make_common_lisp_symbol("PROBE-FILE");
  symbol_proclaim = make_common_lisp_symbol("PROCLAIM");
  symbol_prog = make_common_lisp_symbol("PROG");
  symbol_prog_star = make_common_lisp_symbol("PROG*");
  symbol_prog1 = make_common_lisp_symbol("PROG1");
  symbol_prog2 = make_common_lisp_symbol("PROG2");
  symbol_progn = make_common_lisp_symbol("PROGN");
  symbol_program_error = make_common_lisp_symbol("PROGRAM-ERROR");
  symbol_progv = make_common_lisp_symbol("PROGV");
  symbol_provide = make_common_lisp_symbol("PROVIDE");
  symbol_psetf = make_common_lisp_symbol("PSETF");
  symbol_psetq = make_common_lisp_symbol("PSETQ");
  symbol_push = make_common_lisp_symbol("PUSH");
  symbol_pushnew = make_common_lisp_symbol("PUSHNEW");
  symbol_quote = make_common_lisp_symbol("QUOTE");
  symbol_random = make_common_lisp_symbol("RANDOM");
  symbol_random_state = make_common_lisp_symbol("RANDOM-STATE");
  symbol_random_state_p = make_common_lisp_symbol("RANDOM-STATE-P");
  symbol_rassoc = make_common_lisp_symbol("RASSOC");
  symbol_rassoc_if = make_common_lisp_symbol("RASSOC-IF");
  symbol_rassoc_if_not = make_common_lisp_symbol("RASSOC-IF-NOT");
  symbol_ratio = make_common_lisp_symbol("RATIO");
  symbol_rational = make_common_lisp_symbol("RATIONAL");
  symbol_rationalize = make_common_lisp_symbol("RATIONALIZE");
  symbol_rationalp = make_common_lisp_symbol("RATIONALP");
  symbol_read = make_common_lisp_symbol("READ");
  symbol_read_byte = make_common_lisp_symbol("READ-BYTE");
  symbol_read_char = make_common_lisp_symbol("READ-CHAR");
  symbol_read_char_no_hang = make_common_lisp_symbol("READ-CHAR-NO-HANG");
  symbol_read_delimited_list = make_common_lisp_symbol("READ-DELIMITED-LIST");
  symbol_read_from_string = make_common_lisp_symbol("READ-FROM-STRING");
  symbol_read_line = make_common_lisp_symbol("READ-LINE");
  symbol_read_preserving_whitespace = make_common_lisp_symbol("READ-PRESERVING-WHITESPACE");
  symbol_read_sequence = make_common_lisp_symbol("READ-SEQUENCE");
  symbol_reader_error = make_common_lisp_symbol("READER-ERROR");
  symbol_readtable = make_common_lisp_symbol("READTABLE");
  symbol_readtable_case = make_common_lisp_symbol("READTABLE-CASE");
  symbol_readtablep = make_common_lisp_symbol("READTABLEP");
  symbol_real = make_common_lisp_symbol("REAL");
  symbol_realp = make_common_lisp_symbol("REALP");
  symbol_realpart = make_common_lisp_symbol("REALPART");
  symbol_reduce = make_common_lisp_symbol("REDUCE");
  symbol_reinitialize_instance = make_common_lisp_symbol("REINITIALIZE-INSTANCE");
  symbol_rem = make_common_lisp_symbol("REM");
  symbol_remf = make_common_lisp_symbol("REMF");
  symbol_remhash = make_common_lisp_symbol("REMHASH");
  symbol_remove = make_common_lisp_symbol("REMOVE");
  symbol_remove_duplicates = make_common_lisp_symbol("REMOVE-DUPLICATES");
  symbol_remove_if = make_common_lisp_symbol("REMOVE-IF");
  symbol_remove_if_not = make_common_lisp_symbol("REMOVE-IF-NOT");
  symbol_remove_method = make_common_lisp_symbol("REMOVE-METHOD");
  symbol_remprop = make_common_lisp_symbol("REMPROP");
  symbol_rename_file = make_common_lisp_symbol("RENAME-FILE");
  symbol_rename_package = make_common_lisp_symbol("RENAME-PACKAGE");
  symbol_replace = make_common_lisp_symbol("REPLACE");
  symbol_require = make_common_lisp_symbol("REQUIRE");
  symbol_rest = make_common_lisp_symbol("REST");
  symbol_restart = make_common_lisp_symbol("RESTART");
  symbol_restart_bind = make_common_lisp_symbol("RESTART-BIND");
  symbol_restart_case = make_common_lisp_symbol("RESTART-CASE");
  symbol_restart_name = make_common_lisp_symbol("RESTART-NAME");
  symbol_return = make_common_lisp_symbol("RETURN");
  symbol_return_from = make_common_lisp_symbol("RETURN-FROM");
  symbol_revappend = make_common_lisp_symbol("REVAPPEND");
  symbol_reverse = make_common_lisp_symbol("REVERSE");
  symbol_room = make_common_lisp_symbol("ROOM");
  symbol_rotatef = make_common_lisp_symbol("ROTATEF");
  symbol_round = make_common_lisp_symbol("ROUND");
  symbol_row_major_aref = make_common_lisp_symbol("ROW-MAJOR-AREF");
  symbol_rplaca = make_common_lisp_symbol("RPLACA");
  symbol_rplacd = make_common_lisp_symbol("RPLACD");
  symbol_safety = make_common_lisp_symbol("SAFETY");
  symbol_satisfies = make_common_lisp_symbol("SATISFIES");
  symbol_sbit = make_common_lisp_symbol("SBIT");
  symbol_scale_float = make_common_lisp_symbol("SCALE-FLOAT");
  symbol_schar = make_common_lisp_symbol("SCHAR");
  symbol_search = make_common_lisp_symbol("SEARCH");
  symbol_second = make_common_lisp_symbol("SECOND");
  symbol_sequence = make_common_lisp_symbol("SEQUENCE");
  symbol_serious_condition = make_common_lisp_symbol("SERIOUS-CONDITION");
  symbol_set = make_common_lisp_symbol("SET");
  symbol_set_difference = make_common_lisp_symbol("SET-DIFFERENCE");
  symbol_set_dispatch_macro_character = make_common_lisp_symbol("SET-DISPATCH-MACRO-CHARACTER");
  symbol_set_exclusive_or = make_common_lisp_symbol("SET-EXCLUSIVE-OR");
  symbol_set_macro_character = make_common_lisp_symbol("SET-MACRO-CHARACTER");
  symbol_set_pprint_dispatch = make_common_lisp_symbol("SET-PPRINT-DISPATCH");
  symbol_set_syntax_from_char = make_common_lisp_symbol("SET-SYNTAX-FROM-CHAR");
  symbol_setf = make_common_lisp_symbol("SETF");
  symbol_setq = make_common_lisp_symbol("SETQ");
  symbol_seventh = make_common_lisp_symbol("SEVENTH");
  symbol_shadow = make_common_lisp_symbol("SHADOW");
  symbol_shadowing_import = make_common_lisp_symbol("SHADOWING-IMPORT");
  symbol_shared_initialize = make_common_lisp_symbol("SHARED-INITIALIZE");
  symbol_shiftf = make_common_lisp_symbol("SHIFTF");
  symbol_short_float = make_common_lisp_symbol("SHORT-FLOAT");
  symbol_short_float_epsilon = make_common_lisp_symbol("SHORT-FLOAT-EPSILON");
  symbol_short_float_negative_epsilon = make_common_lisp_symbol("SHORT-FLOAT-NEGATIVE-EPSILON");
  symbol_short_site_name = make_common_lisp_symbol("SHORT-SITE-NAME");
  symbol_signal = make_common_lisp_symbol("SIGNAL");
  symbol_signed_byte = make_common_lisp_symbol("SIGNED-BYTE");
  symbol_signum = make_common_lisp_symbol("SIGNUM");
  symbol_simple_array = make_common_lisp_symbol("SIMPLE-ARRAY");
  symbol_simple_base_string = make_common_lisp_symbol("SIMPLE-BASE-STRING");
  symbol_simple_bit_vector = make_common_lisp_symbol("SIMPLE-BIT-VECTOR");
  symbol_simple_bit_vector_p = make_common_lisp_symbol("SIMPLE-BIT-VECTOR-P");
  symbol_simple_condition = make_common_lisp_symbol("SIMPLE-CONDITION");
  symbol_simple_condition_format_arguments = make_common_lisp_symbol("SIMPLE-CONDITION-FORMAT-ARGUMENTS");
  symbol_simple_condition_format_control = make_common_lisp_symbol("SIMPLE-CONDITION-FORMAT-CONTROL");
  symbol_simple_error = make_common_lisp_symbol("SIMPLE-ERROR");
  symbol_simple_string = make_common_lisp_symbol("SIMPLE-STRING");
  symbol_simple_string_p = make_common_lisp_symbol("SIMPLE-STRING-P");
  symbol_simple_type_error = make_common_lisp_symbol("SIMPLE-TYPE-ERROR");
  symbol_simple_vector = make_common_lisp_symbol("SIMPLE-VECTOR");
  symbol_simple_vector_p = make_common_lisp_symbol("SIMPLE-VECTOR-P");
  symbol_simple_warning = make_common_lisp_symbol("SIMPLE-WARNING");
  symbol_sin = make_common_lisp_symbol("SIN");
  symbol_single_float = make_common_lisp_symbol("SINGLE-FLOAT");
  symbol_single_float_epsilon = make_common_lisp_symbol("SINGLE-FLOAT-EPSILON");
  symbol_single_float_negative_epsilon = make_common_lisp_symbol("SINGLE-FLOAT-NEGATIVE-EPSILON");
  symbol_sinh = make_common_lisp_symbol("SINH");
  symbol_sixth = make_common_lisp_symbol("SIXTH");
  symbol_sleep = make_common_lisp_symbol("SLEEP");
  symbol_slot_boundp = make_common_lisp_symbol("SLOT-BOUNDP");
  symbol_slot_exists_p = make_common_lisp_symbol("SLOT-EXISTS-P");
  symbol_slot_makunbound = make_common_lisp_symbol("SLOT-MAKUNBOUND");
  symbol_slot_missing = make_common_lisp_symbol("SLOT-MISSING");
  symbol_slot_unbound = make_common_lisp_symbol("SLOT-UNBOUND");
  symbol_slot_value = make_common_lisp_symbol("SLOT-VALUE");
  symbol_software_type = make_common_lisp_symbol("SOFTWARE-TYPE");
  symbol_software_version = make_common_lisp_symbol("SOFTWARE-VERSION");
  symbol_some = make_common_lisp_symbol("SOME");
  symbol_sort = make_common_lisp_symbol("SORT");
  symbol_space = make_common_lisp_symbol("SPACE");
  symbol_special = make_common_lisp_symbol("SPECIAL");
  symbol_special_operator_p = make_common_lisp_symbol("SPECIAL-OPERATOR-P");
  symbol_speed = make_common_lisp_symbol("SPEED");
  symbol_sqrt = make_common_lisp_symbol("SQRT");
  symbol_stable_sort = make_common_lisp_symbol("STABLE-SORT");
  symbol_standard = make_common_lisp_symbol("STANDARD");
  symbol_standard_char = make_common_lisp_symbol("STANDARD-CHAR");
  symbol_standard_char_p = make_common_lisp_symbol("STANDARD-CHAR-P");
  symbol_standard_class = make_common_lisp_symbol("STANDARD-CLASS");
  symbol_standard_generic_function = make_common_lisp_symbol("STANDARD-GENERIC-FUNCTION");
  symbol_standard_method = make_common_lisp_symbol("STANDARD-METHOD");
  symbol_standard_object = make_common_lisp_symbol("STANDARD-OBJECT");
  symbol_step = make_common_lisp_symbol("STEP");
  symbol_storage_condition = make_common_lisp_symbol("STORAGE-CONDITION");
  symbol_store_value = make_common_lisp_symbol("STORE-VALUE");
  symbol_stream = make_common_lisp_symbol("STREAM");
  symbol_stream_element_type = make_common_lisp_symbol("STREAM-ELEMENT-TYPE");
  symbol_stream_error = make_common_lisp_symbol("STREAM-ERROR");
  symbol_stream_error_stream = make_common_lisp_symbol("STREAM-ERROR-STREAM");
  symbol_stream_external_format = make_common_lisp_symbol("STREAM-EXTERNAL-FORMAT");
  symbol_streamp = make_common_lisp_symbol("STREAMP");
  symbol_string = make_common_lisp_symbol("STRING");
  symbol_string_capitalize = make_common_lisp_symbol("STRING-CAPITALIZE");
  symbol_string_downcase = make_common_lisp_symbol("STRING-DOWNCASE");
  symbol_string_equal = make_common_lisp_symbol("STRING-EQUAL");
  symbol_string_greaterp = make_common_lisp_symbol("STRING-GREATERP");
  symbol_string_left_trim = make_common_lisp_symbol("STRING-LEFT-TRIM");
  symbol_string_lessp = make_common_lisp_symbol("STRING-LESSP");
  symbol_string_not_equal = make_common_lisp_symbol("STRING-NOT-EQUAL");
  symbol_string_not_greaterp = make_common_lisp_symbol("STRING-NOT-GREATERP");
  symbol_string_not_lessp = make_common_lisp_symbol("STRING-NOT-LESSP");
  symbol_string_right_trim = make_common_lisp_symbol("STRING-RIGHT-TRIM");
  symbol_string_stream = make_common_lisp_symbol("STRING-STREAM");
  symbol_string_trim = make_common_lisp_symbol("STRING-TRIM");
  symbol_string_upcase = make_common_lisp_symbol("STRING-UPCASE");
  symbol_string_slash_equal = make_common_lisp_symbol("STRING/=");
  symbol_string_less_than_sign = make_common_lisp_symbol("STRING<");
  symbol_string_less_than_or_equal_sign = make_common_lisp_symbol("STRING<=");
  symbol_string_equal_sign = make_common_lisp_symbol("STRING=");
  symbol_string_greater_than_sign = make_common_lisp_symbol("STRING>");
  symbol_string_greater_than_or_equal_sign = make_common_lisp_symbol("STRING>=");
  symbol_stringp = make_common_lisp_symbol("STRINGP");
  symbol_structure = make_common_lisp_symbol("STRUCTURE");
  symbol_structure_class = make_common_lisp_symbol("STRUCTURE-CLASS");
  symbol_structure_object = make_common_lisp_symbol("STRUCTURE-OBJECT");
  symbol_style_warning = make_common_lisp_symbol("STYLE-WARNING");
  symbol_sublis = make_common_lisp_symbol("SUBLIS");
  symbol_subseq = make_common_lisp_symbol("SUBSEQ");
  symbol_subsetp = make_common_lisp_symbol("SUBSETP");
  symbol_subst = make_common_lisp_symbol("SUBST");
  symbol_subst_if = make_common_lisp_symbol("SUBST-IF");
  symbol_subst_if_not = make_common_lisp_symbol("SUBST-IF-NOT");
  symbol_substitute = make_common_lisp_symbol("SUBSTITUTE");
  symbol_substitute_if = make_common_lisp_symbol("SUBSTITUTE-IF");
  symbol_substitute_if_not = make_common_lisp_symbol("SUBSTITUTE-IF-NOT");
  symbol_subtypep = make_common_lisp_symbol("SUBTYPEP");
  symbol_svref = make_common_lisp_symbol("SVREF");
  symbol_sxhash = make_common_lisp_symbol("SXHASH");
  symbol_symbol = make_common_lisp_symbol("SYMBOL");
  symbol_symbol_function = make_common_lisp_symbol("SYMBOL-FUNCTION");
  symbol_symbol_macrolet = make_common_lisp_symbol("SYMBOL-MACROLET");
  symbol_symbol_name = make_common_lisp_symbol("SYMBOL-NAME");
  symbol_symbol_package = make_common_lisp_symbol("SYMBOL-PACKAGE");
  symbol_symbol_plist = make_common_lisp_symbol("SYMBOL-PLIST");
  symbol_symbol_value = make_common_lisp_symbol("SYMBOL-VALUE");
  symbol_symbolp = make_common_lisp_symbol("SYMBOLP");
  symbol_synonym_stream = make_common_lisp_symbol("SYNONYM-STREAM");
  symbol_synonym_stream_symbol = make_common_lisp_symbol("SYNONYM-STREAM-SYMBOL");
  symbol_t = make_common_lisp_symbol("T");
  symbol_tagbody = make_common_lisp_symbol("TAGBODY");
  symbol_tailp = make_common_lisp_symbol("TAILP");
  symbol_tan = make_common_lisp_symbol("TAN");
  symbol_tanh = make_common_lisp_symbol("TANH");
  symbol_tenth = make_common_lisp_symbol("TENTH");
  symbol_terpri = make_common_lisp_symbol("TERPRI");
  symbol_the = make_common_lisp_symbol("THE");
  symbol_third = make_common_lisp_symbol("THIRD");
  symbol_throw = make_common_lisp_symbol("THROW");
  symbol_time = make_common_lisp_symbol("TIME");
  symbol_trace = make_common_lisp_symbol("TRACE");
  symbol_translate_logical_pathname = make_common_lisp_symbol("TRANSLATE-LOGICAL-PATHNAME");
  symbol_translate_pathname = make_common_lisp_symbol("TRANSLATE-PATHNAME");
  symbol_tree_equal = make_common_lisp_symbol("TREE-EQUAL");
  symbol_truename = make_common_lisp_symbol("TRUENAME");
  symbol_truncate = make_common_lisp_symbol("TRUNCATE");
  symbol_two_way_stream = make_common_lisp_symbol("TWO-WAY-STREAM");
  symbol_two_way_stream_input_stream = make_common_lisp_symbol("TWO-WAY-STREAM-INPUT-STREAM");
  symbol_two_way_stream_output_stream = make_common_lisp_symbol("TWO-WAY-STREAM-OUTPUT-STREAM");
  symbol_type = make_common_lisp_symbol("TYPE");
  symbol_type_error = make_common_lisp_symbol("TYPE-ERROR");
  symbol_type_error_datum = make_common_lisp_symbol("TYPE-ERROR-DATUM");
  symbol_type_error_expected_type = make_common_lisp_symbol("TYPE-ERROR-EXPECTED-TYPE");
  symbol_type_of = make_common_lisp_symbol("TYPE-OF");
  symbol_typecase = make_common_lisp_symbol("TYPECASE");
  symbol_typep = make_common_lisp_symbol("TYPEP");
  symbol_unbound_slot = make_common_lisp_symbol("UNBOUND-SLOT");
  symbol_unbound_slot_instance = make_common_lisp_symbol("UNBOUND-SLOT-INSTANCE");
  symbol_unbound_variable = make_common_lisp_symbol("UNBOUND-VARIABLE");
  symbol_undefined_function = make_common_lisp_symbol("UNDEFINED-FUNCTION");
  symbol_unexport = make_common_lisp_symbol("UNEXPORT");
  symbol_unintern = make_common_lisp_symbol("UNINTERN");
  symbol_union = make_common_lisp_symbol("UNION");
  symbol_unless = make_common_lisp_symbol("UNLESS");
  symbol_unread_char = make_common_lisp_symbol("UNREAD-CHAR");
  symbol_unsigned_byte = make_common_lisp_symbol("UNSIGNED-BYTE");
  symbol_untrace = make_common_lisp_symbol("UNTRACE");
  symbol_unuse_package = make_common_lisp_symbol("UNUSE-PACKAGE");
  symbol_unwind_protect = make_common_lisp_symbol("UNWIND-PROTECT");
  symbol_update_instance_for_different_class = make_common_lisp_symbol("UPDATE-INSTANCE-FOR-DIFFERENT-CLASS");
  symbol_update_instance_for_redefined_class = make_common_lisp_symbol("UPDATE-INSTANCE-FOR-REDEFINED-CLASS");
  symbol_upgraded_array_element_type = make_common_lisp_symbol("UPGRADED-ARRAY-ELEMENT-TYPE");
  symbol_upgraded_complex_part_type = make_common_lisp_symbol("UPGRADED-COMPLEX-PART-TYPE");
  symbol_upper_case_p = make_common_lisp_symbol("UPPER-CASE-P");
  symbol_use_package = make_common_lisp_symbol("USE-PACKAGE");
  symbol_use_value = make_common_lisp_symbol("USE-VALUE");
  symbol_user_homedir_pathname = make_common_lisp_symbol("USER-HOMEDIR-PATHNAME");
  symbol_values = make_common_lisp_symbol("VALUES");
  symbol_values_list = make_common_lisp_symbol("VALUES-LIST");
  symbol_variable = make_common_lisp_symbol("VARIABLE");
  symbol_vector = make_common_lisp_symbol("VECTOR");
  symbol_vector_pop = make_common_lisp_symbol("VECTOR-POP");
  symbol_vector_push = make_common_lisp_symbol("VECTOR-PUSH");
  symbol_vector_push_extend = make_common_lisp_symbol("VECTOR-PUSH-EXTEND");
  symbol_vectorp = make_common_lisp_symbol("VECTORP");
  symbol_warn = make_common_lisp_symbol("WARN");
  symbol_warning = make_common_lisp_symbol("WARNING");
  symbol_when = make_common_lisp_symbol("WHEN");
  symbol_wild_pathname_p = make_common_lisp_symbol("WILD-PATHNAME-P");
  symbol_with_accessors = make_common_lisp_symbol("WITH-ACCESSORS");
  symbol_with_compilation_unit = make_common_lisp_symbol("WITH-COMPILATION-UNIT");
  symbol_with_condition_restarts = make_common_lisp_symbol("WITH-CONDITION-RESTARTS");
  symbol_with_hash_table_iterator = make_common_lisp_symbol("WITH-HASH-TABLE-ITERATOR");
  symbol_with_input_from_string = make_common_lisp_symbol("WITH-INPUT-FROM-STRING");
  symbol_with_open_file = make_common_lisp_symbol("WITH-OPEN-FILE");
  symbol_with_open_stream = make_common_lisp_symbol("WITH-OPEN-STREAM");
  symbol_with_output_to_string = make_common_lisp_symbol("WITH-OUTPUT-TO-STRING");
  symbol_with_package_iterator = make_common_lisp_symbol("WITH-PACKAGE-ITERATOR");
  symbol_with_simple_restart = make_common_lisp_symbol("WITH-SIMPLE-RESTART");
  symbol_with_slots = make_common_lisp_symbol("WITH-SLOTS");
  symbol_with_standard_io_syntax = make_common_lisp_symbol("WITH-STANDARD-IO-SYNTAX");
  symbol_write = make_common_lisp_symbol("WRITE");
  symbol_write_byte = make_common_lisp_symbol("WRITE-BYTE");
  symbol_write_char = make_common_lisp_symbol("WRITE-CHAR");
  symbol_write_line = make_common_lisp_symbol("WRITE-LINE");
  symbol_write_sequence = make_common_lisp_symbol("WRITE-SEQUENCE");
  symbol_write_string = make_common_lisp_symbol("WRITE-STRING");
  symbol_write_to_string = make_common_lisp_symbol("WRITE-TO-STRING");
  symbol_y_or_n_p = make_common_lisp_symbol("Y-OR-N-P");
  symbol_yes_or_no_p = make_common_lisp_symbol("YES-OR-NO-P");
  symbol_zerop = make_common_lisp_symbol("ZEROP");
  symbol_ampersand_allow_other_keys = make_common_lisp_symbol("&ALLOW-OTHER-KEYS");
  symbol_ampersand_aux = make_common_lisp_symbol("&AUX");
  symbol_ampersand_body = make_common_lisp_symbol("&BODY");
  symbol_ampersand_environment = make_common_lisp_symbol("&ENVIRONMENT");
  symbol_ampersand_key = make_common_lisp_symbol("&KEY");
  symbol_ampersand_optional = make_common_lisp_symbol("&OPTIONAL");
  symbol_ampersand_rest = make_common_lisp_symbol("&REST");
  symbol_ampersand_whole = make_common_lisp_symbol("&WHOLE");
  symbol_star = make_common_lisp_symbol("*");
  symbol_star_star = make_common_lisp_symbol("**");
  symbol_star_star_star = make_common_lisp_symbol("***");
  symbol_star_break_on_signals_star = make_common_lisp_symbol("*BREAK-ON-SIGNALS*");
  symbol_star_compile_file_pathname_star = make_common_lisp_symbol("*COMPILE-FILE-PATHNAME*");
  symbol_star_compile_file_truename_star = make_common_lisp_symbol("*COMPILE-FILE-TRUENAME*");
  symbol_star_compile_print_star = make_common_lisp_symbol("*COMPILE-PRINT*");
  symbol_star_compile_verbose_star = make_common_lisp_symbol("*COMPILE-VERBOSE*");
  symbol_star_debug_io_star = make_common_lisp_symbol("*DEBUG-IO*");
  symbol_star_debugger_hook_star = make_common_lisp_symbol("*DEBUGGER-HOOK*");
  symbol_star_default_pathname_defaults_star = make_common_lisp_symbol("*DEFAULT-PATHNAME-DEFAULTS*");
  symbol_star_error_output_star = make_common_lisp_symbol("*ERROR-OUTPUT*");
  symbol_star_features_star = make_common_lisp_symbol("*FEATURES*");
  symbol_star_gensym_counter_star = make_common_lisp_symbol("*GENSYM-COUNTER*");
  symbol_star_load_pathname_star = make_common_lisp_symbol("*LOAD-PATHNAME*");
  symbol_star_load_print_star = make_common_lisp_symbol("*LOAD-PRINT*");
  symbol_star_load_truename_star = make_common_lisp_symbol("*LOAD-TRUENAME*");
  symbol_star_load_verbose_star = make_common_lisp_symbol("*LOAD-VERBOSE*");
  symbol_star_macroexpand_hook_star = make_common_lisp_symbol("*MACROEXPAND-HOOK*");
  symbol_star_modules_star = make_common_lisp_symbol("*MODULES*");
  symbol_star_package_star = make_common_lisp_symbol("*PACKAGE*");
  symbol_star_print_array_star = make_common_lisp_symbol("*PRINT-ARRAY*");
  symbol_star_print_base_star = make_common_lisp_symbol("*PRINT-BASE*");
  symbol_star_print_case_star = make_common_lisp_symbol("*PRINT-CASE*");
  symbol_star_print_circle_star = make_common_lisp_symbol("*PRINT-CIRCLE*");
  symbol_star_print_escape_star = make_common_lisp_symbol("*PRINT-ESCAPE*");
  symbol_star_print_gensym_star = make_common_lisp_symbol("*PRINT-GENSYM*");
  symbol_star_print_length_star = make_common_lisp_symbol("*PRINT-LENGTH*");
  symbol_star_print_level_star = make_common_lisp_symbol("*PRINT-LEVEL*");
  symbol_star_print_lines_star = make_common_lisp_symbol("*PRINT-LINES*");
  symbol_star_print_miser_width_star = make_common_lisp_symbol("*PRINT-MISER-WIDTH*");
  symbol_star_print_pprint_dispatch_star = make_common_lisp_symbol("*PRINT-PPRINT-DISPATCH*");
  symbol_star_print_pretty_star = make_common_lisp_symbol("*PRINT-PRETTY*");
  symbol_star_print_radix_star = make_common_lisp_symbol("*PRINT-RADIX*");
  symbol_star_print_readably_star = make_common_lisp_symbol("*PRINT-READABLY*");
  symbol_star_print_right_margin_star = make_common_lisp_symbol("*PRINT-RIGHT-MARGIN*");
  symbol_star_query_io_star = make_common_lisp_symbol("*QUERY-IO*");
  symbol_star_random_state_star = make_common_lisp_symbol("*RANDOM-STATE*");
  symbol_star_read_base_star = make_common_lisp_symbol("*READ-BASE*");
  symbol_star_read_default_float_format_star = make_common_lisp_symbol("*READ-DEFAULT-FLOAT-FORMAT*");
  symbol_star_read_eval_star = make_common_lisp_symbol("*READ-EVAL*");
  symbol_star_read_suppress_star = make_common_lisp_symbol("*READ-SUPPRESS*");
  symbol_star_readtable_star = make_common_lisp_symbol("*READTABLE*");
  symbol_star_standard_input_star = make_common_lisp_symbol("*STANDARD-INPUT*");
  symbol_star_standard_output_star = make_common_lisp_symbol("*STANDARD-OUTPUT*");
  symbol_star_terminal_io_star = make_common_lisp_symbol("*TERMINAL-IO*");
  symbol_star_trace_output_star = make_common_lisp_symbol("*TRACE-OUTPUT*");
  symbol_plus = make_common_lisp_symbol("+");
  symbol_plus_plus = make_common_lisp_symbol("++");
  symbol_plus_plus_plus = make_common_lisp_symbol("+++");
  symbol_minus = make_common_lisp_symbol("-");
  symbol_slash = make_common_lisp_symbol("/");
  symbol_slash_slash = make_common_lisp_symbol("//");
  symbol_slash_slash_slash = make_common_lisp_symbol("///");
  symbol_slash_equal = make_common_lisp_symbol("/=");
  symbol_one_plus = make_common_lisp_symbol("1+");
  symbol_one_minus = make_common_lisp_symbol("1-");
  symbol_less_than_sign = make_common_lisp_symbol("<");
  symbol_less_than_or_equal_sign = make_common_lisp_symbol("<=");
  symbol_equal_sign = make_common_lisp_symbol("=");
  symbol_greater_than_sign = make_common_lisp_symbol(">");
  symbol_greater_than_or_equal_sign = make_common_lisp_symbol(">=");

  keyword_datum = make_keyword_symbol("DATUM");
  keyword_expected_type = make_keyword_symbol("EXPECTED-TYPE");

  symbol_initialized_p = 1;
}
